In [1]:
import pandas as pd

## read data

In [2]:
odourresponse_s1 = pd.read_csv('data\Hallem_Carlson_2006\Hallem_Carlson_2006_S1.csv')
odourresponse_s1

,odour,2a,7a,9a,10a,19a,22a,23a,33b,35a,...,59b,65a,67a,67c,82a,85a,85b,85f,88a,98a
0,ammonium hydroxide,3,-21,32,10,1,13,-2,-9,4,...,5,3,16,10,2,-6,15,17,0,24
1,putrescine,6,-36,26,-26,-9,12,-2,-4,0,...,2,-2,-4,6,-4,-13,24,8,-6,17
2,cadaverine,1,-41,21,-17,-5,13,-7,-7,12,...,7,-1,-8,14,-2,-11,29,16,0,21
3,g-butyrolactone,9,34,53,-6,-7,43,4,7,81,...,16,6,125,20,-7,-8,47,23,2,29
4,g-hexalactone,15,-39,118,18,-2,140,12,25,171,...,18,18,47,40,5,-3,53,54,3,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,ethyl decanoate,5,-12,2,43,-17,6,-1,1,-10,...,3,-4,-7,-3,-4,-20,28,-2,-5,12
107,ethyl trans-2-butenoate,11,-2,103,146,9,210,9,-4,14,...,-7,2,104,34,16,91,80,24,-9,243
108,ethyl lactate,39,31,75,31,24,70,11,2,5,...,133,31,39,288,42,39,77,77,-7,66
109,diethyl succinate,16,-11,21,-13,24,205,26,-8,-20,...,-9,5,175,7,32,-12,35,12,5,4
110,spontaneous firing rate,8,17,3,14,29,4,9,25,17,...,2,18,11,6,16,14,13,7,26,12

In [3]:
odourdilution = pd.read_csv('data\Hallem_Carlson_2006\Hallem_Carlson_2006_S2.csv')
odourdilution

,odour,dilution,2a,7a,9a,10a,19a,22a,23a,33b,...,59b,65a,67a,67c,82a,85a,85b,85f,88a,98a
0,ethyl acetate,-2.0,-3,6,37,6,7,53,2,10,...,177,0,43,29,17,65,18,12,5,23
1,pentyl acetate,-2.0,35,-4,85,-1,130,158,20,-12,...,65,34,216,17,21,30,190,35,9,191
2,ethyl butyrate,-2.0,12,1,121,29,73,193,15,37,...,39,-8,167,112,27,125,102,26,-9,81
3,methyl salicylate,-2.0,5,-6,13,258,1,-2,-1,-7,...,-4,-13,35,-2,-5,2,-8,5,-7,8
4,1-hexanol,-2.0,40,96,102,10,146,63,51,1,...,35,7,173,109,58,137,183,64,16,158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,mango,-6.0,-5,6,1,3,-7,4,2,-6,...,1,-4,3,-12,-2,0,-5,-7,-1,-5
72,peach,-6.0,0,0,0,9,-7,0,1,-8,...,0,-1,-2,-6,-9,-1,-3,-6,1,-5
73,pineapple,-6.0,-5,1,-1,4,0,1,3,-2,...,3,0,10,-3,-8,-3,-3,-6,-5,-6
74,raspberry,-6.0,3,1,1,10,-7,-1,-3,-5,...,-2,-1,5,-1,-2,1,-6,-1,-3,-2
75,strawberry,-6.0,-3,-4,2,6,1,5,0,-3,...,3,-1,-1,-2,-5,-1,-7,-6,-6,-3

In [4]:
odourtime = pd.read_csv('data\Hallem_Carlson_2006\Hallem_Carlson_2006_S3.csv')
odourtime['odour'] = odourtime.odour.str.replace("Responses to ", "")
odourtime

    receptor    0.0s    0.5s    1.0s    1.5s                      odour
0      Or10a  264.33  233.00  218.67  200.67  methyl salicylate at 10-2
1      Or19a   53.67   23.67   21.67   16.33  methyl salicylate at 10-2
2      Or49b   48.33    0.00    0.33    0.67  methyl salicylate at 10-2
3      Or43a   47.33    3.33    0.33    7.00  methyl salicylate at 10-2
4      Or67a   34.67    1.00   -3.00   -0.67  methyl salicylate at 10-2
..       ...     ...     ...     ...     ...                        ...
187    Or85f   13.00    4.00   -1.00    1.00              apple at 10-4
188    Or33b    0.00   -3.00    5.00    6.67              apple at 10-4
189    Or49b    1.33    3.00   -1.67    0.00              apple at 10-4
190    Or88a   -2.67   -2.67    2.33    2.67              apple at 10-4
191    Or47b  -10.00   -4.33   -1.67    0.00              apple at 10-4

[192 rows x 6 columns]

## S1

In [5]:
# borrow the receptor to glomerulus mapping from DoOR 
odour_mappings = pd.read_csv('data\DoOR\door_receptor_mappings.csv', index_col=0)
receptor_to_glomerulus = dict(zip(odour_mappings['receptor'], odour_mappings['glomerulus']))
odour_mappings

,receptor,sensillum,OSN,glomerulus,co.receptor,coexpressing,related1,related2,related3,related4,related5,related6,Ors,sensillum.type,adult,larva,dataset.existing,comment,code,code.OSN
1,?,?,?,VA7m,?,NaN,NaN,NaN,NaN,NaN,NaN,NaN,?,NaN,NaN,NaN,False,NaN,VA7m,NaN
2,Or42b,ab1,ab1A,DM1,Orco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Or42b,antennal basiconic,True,True,True,NaN,DM1,ab1A
3,Or92a,ab1,ab1B,VA2,Orco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Or92a,antennal basiconic,True,NaN,True,NaN,VA2,ab1B
4,Gr21a.Gr63a,ab1,ab1C,V,NaN,Gr21a+Gr63a,NaN,NaN,NaN,NaN,NaN,NaN,Gr21a+Gr63a,antennal basiconic,True,True,True,NaN,V,ab1C
5,Or10a,ab1,ab1D,DL1,Orco,Gr10a,Gr10a,NaN,NaN,NaN,NaN,NaN,Or10a+Gr10a,antennal basiconic,True,NaN,True,NaN,DL1,ab1D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,Or83a,NaN,NaN,NaN,Orco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True,True,NaN,NaN,NaN
93,Or83b,NaN,NaN,NaN,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,False,the Orco co-receptor expressed together with a...,NaN,NaN
94,Or85c,NaN,NaN,NaN,Orco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True,True,NaN,NaN,NaN
95,Or94a,NaN,NaN,NaN,Orco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True,True,NaN,NaN,NaN
96,Or94b,NaN,NaN,NaN,Orco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True,True,NaN,NaN,NaN

In [6]:
# anything present in the Hallem & Carlson data that is not in DoOR?
set('Or'+odourresponse_s1.columns[1:]) - set(odour_mappings.receptor[odour_mappings.adult == True])

set()

In [7]:
# map to glomerulus 
odourresponse_s1.columns = [odourresponse_s1.columns[0]] + list(
    "Or" + odourresponse_s1.columns[1:]
)
odourresponse_s1 = odourresponse_s1.rename(columns=receptor_to_glomerulus)
odourresponse_s1.set_index('odour', inplace=True)
odourresponse_s1 = odourresponse_s1.T
odourresponse_s1

odour,ammonium hydroxide,putrescine,cadaverine,g-butyrolactone,g-hexalactone,g-octalactone,g-decalactone,d-decalactone,methanoic acid,acetic acid,...,methyl hexanoate,ethyl hexanoate,hexyl hexanoate,methyl octanoate,ethyl octanoate,ethyl decanoate,ethyl trans-2-butenoate,ethyl lactate,diethyl succinate,spontaneous firing rate
DA4m,3,6,1,9,15,7,-1,0,-2,5,...,39,22,1,1,1,5,11,39,16,8
DL5,-21,-36,-41,34,-39,-22,-12,-15,-14,-11,...,40,-13,-4,-7,-7,-12,-2,31,-11,17
VM3,32,26,21,53,118,26,-1,-2,14,9,...,53,20,-3,4,2,2,103,75,21,3
DL1,10,-26,-17,-6,18,18,-2,-11,31,18,...,17,-14,-1,-13,-14,43,146,31,-13,14
DC1,1,-9,-5,-7,-2,2,-22,-23,0,3,...,36,42,-25,0,-8,-17,9,24,24,29
DM2,13,12,13,43,140,41,16,11,33,32,...,256,224,31,237,95,6,210,70,205,4
DA3,-2,-2,-7,4,12,3,-3,-2,-8,-1,...,9,13,-4,-3,-4,-1,9,11,26,9
DM5+DM3,-9,-4,-7,7,25,10,17,15,-6,-2,...,-16,0,1,3,-4,1,-4,2,-8,25
VC3,4,0,12,81,171,36,-3,-10,5,-1,...,-10,-21,126,10,-12,-10,14,5,-20,17
DA4l,-1,-17,-10,-12,8,-5,-18,-16,-9,0,...,3,6,-14,-13,-12,-8,-22,7,-8,21
VM2,3,1,12,19,30,27,2,2,8,10,...,58,4,-1,4,3,7,191,93,4,2
DM3,16,-9,-8,6,24,17,-3,0,-1,2,...,210,138,-1,58,18,-3,44,29,36,1
VA1v,-8,-25,-16,9,-36,-19,-3,-4,-20,-21,...,-33,-31,4,-26,-7,-3,-33,-28,-16,47
VA5,4,-7,-2,-1,-1,-3,0,-4,3,5,...,12,-2,-1,4,-6,-2,3,34,-3,8
DM4,5,2,7,16,18,0,-4,2,25,24,...,2,-8,7,-8,-2,3,-7,133,-9,2
DL3,3,-2,-1,6,18,20,-2,-5,2,4,...,19,7,-2,22,7,-4,2,31,5,18
DM6,16,-4,-8,125,47,25,7,2,5,-5,...,87,143,-3,-7,-10,-7,104,39,175,11
VC4,10,6,14,20,40,16,1,0,12,6,...,21,-3,-4,2,1,-3,34,288,7,6
VA6,2,-4,-2,-7,5,20,-8,-5,-8,10,...,18,10,-3,16,5,-4,16,42,32,16
DM5,-6,-13,-11,-8,-3,-13,-11,1,-9,1,...,-16,-22,5,-12,-8,-20,91,39,-12,14
VM5d,15,24,29,47,53,174,13,24,14,27,...,228,89,17,62,39,28,80,77,35,13
DL4,17,8,16,23,54,31,-5,-1,7,11,...,33,10,9,1,1,-2,24,77,12,7
VA1d,0,-6,0,2,3,-16,7,-1,0,-5,...,-27,-11,3,-8,-5,-5,-9,-7,5,26
VM5v,24,17,21,29,24,101,9,8,4,19,...,188,55,5,23,22,12,243,66,4,12

In [8]:
odourresponse_s1.abs().max(axis=1)

DA4m        65
DL5        221
VM3        247
DL1        268
DC1        149
DM2        256
DA3         73
DM5+DM3     81
VC3        237
DA4l       133
VM2        199
DM3        241
VA1v        47
VA5        250
DM4        269
DL3         49
DM6        236
VC4        288
VA6        241
DM5        210
VM5d       257
DL4         84
VA1d        27
VM5v       273
dtype: int64

We can see that the max firing rate of each glomerulus differs quite a lot. Though there were 100 odours, it might be that none were great for some glomeruli. Assuming ORNs types are more similar than different, maybe should normalise by max firing rate overall.

In [9]:
# which supplement has the max firing rate? 
odourresponse_s1.abs().max().max(), odourdilution.drop(columns=['odour','dilution']).abs().max().max(), odourtime[['0.0s','0.5s','1.0s','1.5s']].abs().max().max()

(288, 264, 264.33)

In [10]:
max_activation = max(
    odourresponse_s1.abs().max().max(),
    odourdilution.drop(columns=["odour", "dilution"]).abs().max().max(),
    odourtime[["0.0s", "0.5s", "1.0s", "1.5s"]].abs().max().max(),
)

In [11]:
# normalise: divide by the maximum absolute response
odourresponse_s1 = odourresponse_s1.div(max_activation)
# save
odourresponse_s1.to_csv('data/Hallem_Carlson_2006/odour_response_s1_tidy.csv')

## S2

In [12]:
# anything present in the Hallem & Carlson data that is not in DoOR?
set("Or" + odourdilution.columns[2:]) - set(
    odour_mappings.receptor[odour_mappings.adult == True]
)

set()

In [13]:
odourdilution.odour.value_counts()

odour
ethyl acetate        4
E2-hexenal           4
pentyl acetate       4
2-heptanone          4
2,3-butanedione      4
geranyl acetate      4
1-octen-3-ol         4
1-hexanol            4
methyl salicylate    4
ethyl butyrate       4
apple                3
raspberry            3
pineapple            3
peach                3
mango                3
cherry               3
banana               3
apricot              3
strawberry           3
strawberry pure      1
raspberry pure       1
pineapple pure       1
peach pure           1
cherry pure          1
banana pure          1
apricot pure         1
apple pure           1
mango pure           1
Name: count, dtype: int64

In [14]:
odourdilution.odour[~odourdilution.odour.str.contains('pure')].nunique()

19

In [15]:
odourdilution["odour_dilution"] = (
    odourdilution["odour"] + " at " + odourdilution["dilution"].astype(str)
)
odourdilution.drop(columns=["odour", "dilution"], inplace=True)
odourdilution

,2a,7a,9a,10a,19a,22a,23a,33b,35a,43a,...,65a,67a,67c,82a,85a,85b,85f,88a,98a,odour_dilution
0,-3,6,37,6,7,53,2,10,18,8,...,0,43,29,17,65,18,12,5,23,ethyl acetate at -2.0
1,35,-4,85,-1,130,158,20,-12,191,12,...,34,216,17,21,30,190,35,9,191,pentyl acetate at -2.0
2,12,1,121,29,73,193,15,37,121,22,...,-8,167,112,27,125,102,26,-9,81,ethyl butyrate at -2.0
3,5,-6,13,258,1,-2,-1,-7,2,20,...,-13,35,-2,-5,2,-8,5,-7,8,methyl salicylate at -2.0
4,40,96,102,10,146,63,51,1,237,133,...,7,173,109,58,137,183,64,16,158,1-hexanol at -2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,-5,6,1,3,-7,4,2,-6,3,3,...,-4,3,-12,-2,0,-5,-7,-1,-5,mango at -6.0
72,0,0,0,9,-7,0,1,-8,6,5,...,-1,-2,-6,-9,-1,-3,-6,1,-5,peach at -6.0
73,-5,1,-1,4,0,1,3,-2,1,12,...,0,10,-3,-8,-3,-3,-6,-5,-6,pineapple at -6.0
74,3,1,1,10,-7,-1,-3,-5,3,8,...,-1,5,-1,-2,1,-6,-1,-3,-2,raspberry at -6.0
75,-3,-4,2,6,1,5,0,-3,2,1,...,-1,-1,-2,-5,-1,-7,-6,-6,-3,strawberry at -6.0

In [16]:
# map to glomerulus
odourdilution.columns = list(
    "Or" + odourdilution.columns[:-1]
) + ["odour_dilution"]
odourdilution = odourdilution.rename(columns=receptor_to_glomerulus)
odourdilution.set_index("odour_dilution", inplace=True)
odourdilution = odourdilution.T
odourdilution

odour_dilution,ethyl acetate at -2.0,pentyl acetate at -2.0,ethyl butyrate at -2.0,methyl salicylate at -2.0,1-hexanol at -2.0,1-octen-3-ol at -2.0,E2-hexenal at -2.0,"2,3-butanedione at -2.0",2-heptanone at -2.0,geranyl acetate at -2.0,...,strawberry at -4.0,apple at -6.0,apricot at -6.0,banana at -6.0,cherry at -6.0,mango at -6.0,peach at -6.0,pineapple at -6.0,raspberry at -6.0,strawberry at -6.0
DA4m,-3,35,12,5,40,27,17,3,39,2,...,17,-1,-2,-3,-4,-5,0,-5,3,-3
DL5,6,-4,1,-6,96,9,221,13,-2,1,...,11,10,6,10,7,6,0,1,1,-4
VM3,37,85,121,13,102,54,38,60,106,-5,...,2,3,-1,1,4,1,0,-1,1,2
DL1,6,-1,29,258,10,-6,-8,22,17,-8,...,2,8,-3,1,3,3,9,4,10,6
DC1,7,130,73,1,146,149,58,35,131,9,...,0,-7,-5,-6,-3,-7,-7,0,-7,1
DM2,53,158,193,-2,63,121,49,48,111,1,...,64,7,-2,1,2,4,0,1,-1,5
DA3,2,20,15,-1,51,19,45,15,25,4,...,-1,1,1,0,2,2,1,3,-3,0
DM5+DM3,10,-12,37,-7,1,-17,-8,11,0,0,...,-1,-8,-6,-4,-2,-6,-8,-2,-5,-3
VC3,18,191,121,2,237,141,227,13,119,-3,...,15,17,8,4,1,3,6,1,3,2
DA4l,8,12,22,20,133,100,41,11,42,-10,...,-5,4,13,12,12,3,5,12,8,1
VM2,132,89,199,12,73,44,84,69,71,10,...,-2,1,-1,-3,5,5,0,5,-3,7
DM3,86,241,74,-6,58,90,37,25,209,-2,...,7,10,6,7,7,12,13,5,3,4
VA1v,-7,-24,-16,6,-35,-30,18,7,-10,-1,...,-4,-12,-10,-8,-7,-6,1,-8,-19,-8
VA5,15,8,-3,48,31,15,6,6,21,-4,...,8,5,1,3,6,6,-3,3,2,2
DM4,177,65,39,-4,35,15,3,97,25,37,...,-1,0,-1,-1,1,1,0,3,-2,3
DL3,0,34,-8,-13,7,16,-2,8,35,-7,...,10,0,-2,-5,-6,-4,-1,0,-1,-1
DM6,43,216,167,35,173,164,117,84,170,7,...,-1,8,6,-4,-5,3,-2,10,5,-1
VC4,29,17,112,-2,109,24,47,42,36,-3,...,3,-5,-7,-2,-6,-12,-6,-3,-1,-2
VA6,17,21,27,-5,58,34,-6,20,32,241,...,8,-8,-2,-2,6,-2,-9,-8,-2,-5
DM5,65,30,125,2,137,40,11,40,33,-1,...,5,-6,-1,-6,-4,0,-1,-3,1,-1
VM5d,18,190,102,-8,183,180,145,71,190,-2,...,18,-3,-6,-6,-2,-5,-3,-3,-6,-7
DL4,12,35,26,5,64,31,35,14,40,-2,...,3,-1,-5,-6,-4,-7,-6,-6,-1,-6
VA1d,5,9,-9,-7,16,-16,-8,11,19,1,...,1,-4,-7,-1,-4,-1,1,-5,-3,-6
VM5v,23,191,81,8,158,197,28,34,189,81,...,-2,4,-2,0,-6,-5,-5,-6,-2,-3

In [17]:
# normalise: divide by the maximum absolute response
odourdilution = odourdilution.div(max_activation)
# save
odourdilution.to_csv("data/Hallem_Carlson_2006/odour_dilution_response_s2_tidy.csv")

## S3

In [18]:
odourtime['glomerulus'] = odourtime.receptor.map(receptor_to_glomerulus)
odourtime[['0.0s', '0.5s', '1.0s', '1.5s']] = odourtime[['0.0s', '0.5s', '1.0s', '1.5s']]/max_activation
odourtime

,receptor,0.0s,0.5s,1.0s,1.5s,odour,glomerulus
0,Or10a,0.917812,0.809028,0.759271,0.696771,methyl salicylate at 10-2,DL1
1,Or19a,0.186354,0.082188,0.075243,0.056701,methyl salicylate at 10-2,DC1
2,Or49b,0.167813,0.000000,0.001146,0.002326,methyl salicylate at 10-2,VA5
3,Or43a,0.164340,0.011562,0.001146,0.024306,methyl salicylate at 10-2,DA4l
4,Or67a,0.120382,0.003472,-0.010417,-0.002326,methyl salicylate at 10-2,DM6
...,...,...,...,...,...,...,...
187,Or85f,0.045139,0.013889,-0.003472,0.003472,apple at 10-4,DL4
188,Or33b,0.000000,-0.010417,0.017361,0.023160,apple at 10-4,DM5+DM3
189,Or49b,0.004618,0.010417,-0.005799,0.000000,apple at 10-4,VA5
190,Or88a,-0.009271,-0.009271,0.008090,0.009271,apple at 10-4,VA1d
191,Or47b,-0.034722,-0.015035,-0.005799,0.000000,apple at 10-4,VA1v

In [19]:
odourtime.odour.unique()

array(['methyl salicylate at 10-2', 'methyl salicylate at 10-4',
       'pentyl acetate at10-2', 'pentyl acetate at10-4',
       '2-heptanone at 10-2', '2-heptanone at 10-4', 'apple at 10-2',
       'apple at 10-4'], dtype=object)

In [20]:
# save 
odourtime.to_csv('data/Hallem_Carlson_2006/odour_time_response_s3_tidy.csv', index=False)