In [1]:
import pandas as pd
import plotly.express as px

In [2]:
result = pd.read_csv("recurrence_results.csv")
result

          pre    post  plen  connected   effconn  effconn_e
0      CB1729  CB1729     1       True  0.002488   0.002488
1      CB1729  CB1729     2       True  0.000484   0.000444
2      CB1729  CB1729     3       True  0.000078   0.000039
3      CB1729  CB1729     4       True  0.000054   0.000012
4      CB1729  CB1729     5       True  0.000038   0.000005
...       ...     ...   ...        ...       ...        ...
44025   PS053   PS053     1      False  0.000000   0.000000
44026   PS053   PS053     2       True  0.004132   0.002492
44027   PS053   PS053     3       True  0.001300   0.000203
44028   PS053   PS053     4       True  0.000805   0.000061
44029   PS053   PS053     5       True  0.000584   0.000019

[44030 rows x 6 columns]

In [3]:
result['plen'] = result['plen'].astype(str)
px.scatter(result[result.connected], x="effconn", y='effconn_e', color='plen', hover_data=['pre'])

In [4]:
across_plen = result.groupby(['pre','connected'])[['effconn','effconn_e']].sum().reset_index()
across_plen.sort_values('effconn_e', ascending=False).head(20)

                pre  connected   effconn  effconn_e
7482       HBeyelet       True  1.535427   1.502883
7590           KCab       True  1.597021   1.456483
1613        BM_InOm       True  1.792008   1.284599
7594       KCapbp-m       True  1.333224   1.257201
9916       SA_VTV_4       True  1.856953   1.253368
7592     KCapbp-ap1       True  1.271296   1.214715
7596          KCg-m       True  1.352169   1.170456
7591         KCab-p       True  1.163843   1.145823
7593     KCapbp-ap2       True  1.092980   1.026795
9077        ORN_VM4       True  1.038169   1.023617
9035        ORN_DA3       True  0.969727   0.961402
9045        ORN_DL3       True  0.946236   0.926602
11589         aPhM6       True  0.859844   0.836599
7562            ITP       True  0.831616   0.831592
9052        ORN_DM5       True  0.827508   0.820010
9117           PFNv       True  0.984555   0.794804
11102         TPMN1       True  1.089484   0.767104
7595          KCg-d       True  0.777685   0.759496
9046        ORN_DL4       True  0.745839   0.739909
693    AN_IPS_GNG_6       True  0.716370   0.714943