Calculate input proportion (i.e. inprop, normalised connectivity) for all of FAFB on a signle neuron level.

In [1]:
import pandas as pd
import numpy as np
from scipy.sparse import coo_matrix
import scipy as sp
import matplotlib.pyplot as plt
import os

# reading data

In [2]:
info = pd.read_csv(
    "https://raw.githubusercontent.com/flyconnectome/flywire_annotations/main/supplemental_files/Supplemental_file1_neuron_annotations.tsv",
    delimiter="\t",
)
root_to_super_class = dict(zip(info["root_id"], info["super_class"]))
info.columns

C:\Users\44745\AppData\Local\Temp\ipykernel_220664\847433904.py:1: DtypeWarning: Columns (15,16,17,23,26,28,29,30) have mixed types. Specify dtype option on import or set low_memory=False.
  info = pd.read_csv(

Index(['supervoxel_id', 'root_id', 'pos_x', 'pos_y', 'pos_z', 'soma_x',
       'soma_y', 'soma_z', 'nucleus_id', 'flow', 'super_class', 'cell_class',
       'cell_sub_class', 'supertype', 'cell_type', 'hemibrain_type',
       'ito_lee_hemilineage', 'hartenstein_hemilineage', 'top_nt',
       'top_nt_conf', 'known_nt', 'known_nt_source', 'side', 'nerve', 'vfb_id',
       'fbbt_id', 'status', 'dimorphism', 'matching_notes', 'fru_dsx',
       'synonyms'],
      dtype='object')

In [3]:
info.super_class.value_counts(dropna=False)

super_class
optic                 77539
central               32384
sensory               16904
visual_projection      8038
ascending              1750
descending             1303
sensory_ascending       612
visual_centrifugal      524
motor                   110
endocrine                80
Name: count, dtype: int64

In [4]:
# read columns, downloaded from here:
# https://codex.flywire.ai/api/download

vis_cols = pd.read_csv(
    "C:/Users/44745/Downloads/column_assignment.csv.gz", compression="gzip"
)
vis_cols

                  root_id hemisphere type  column_id  x   y   p   q
0      720575940603042272      right  Mi1          1 -6  13  12   1
1      720575940603200428      right  Mi1          2 -8   2   9  -7
2      720575940603327916      right  Mi1          3  6 -12 -12   0
3      720575940603935334      right  Mi1          4 -5 -21  -6 -15
4      720575940633953965      right  Mi1          5 -1  16   9   7
...                   ...        ...  ...        ... ..  ..  ..  ..
22679  720575940614768179      right  Tm9        791 -1 -28 -13 -15
22680  720575940617322101      right  Tm9        792  8   2  -7   9
22681  720575940629639674      right  Tm9        793  8  -6 -11   5
22682  720575940634654945      right  Tm9        795  6 -21 -17  -4
22683  720575940616321602      right  Tm9        796  4  26   9  17

[22684 rows x 8 columns]

In [5]:
# visualise the x,y,p,q columns
from connectome_interpreter import *

adf = vis_cols[(vis_cols["type"] == "Mi1")]
adf.set_index("root_id", inplace=True)
# normalise columns
adf.loc[:, ["x"]] = (adf["x"] - adf["x"].min()) / (adf["x"].max() - adf["x"].min())
adf.loc[:, ["y"]] = (adf["y"] - adf["y"].min()) / (adf["y"].max() - adf["y"].min())
adf.loc[:, ["p"]] = (adf["p"] - adf["p"].min()) / (adf["p"].max() - adf["p"].min())
adf.loc[:, ["q"]] = (adf["q"] - adf["q"].min()) / (adf["q"].max() - adf["q"].min())
print(get_ngl_link(adf[["x", "y", "p", "q"]]))

C:\Users\44745\AppData\Local\Temp\ipykernel_220664\1428150344.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.17647059 0.05882353 0.88235294 0.23529412 0.47058824 0.41176471
 0.17647059 0.29411765 0.76470588 0.82352941 0.94117647 0.11764706
 0.47058824 0.52941176 0.64705882 0.41176471 0.58823529 0.82352941
 0.11764706 0.70588235 0.41176471 0.47058824 0.35294118 0.47058824
 0.         0.58823529 0.52941176 0.82352941 0.47058824 0.88235294
 0.52941176 0.52941176 0.70588235 0.88235294 0.58823529 0.88235294
 0.58823529 0.52941176 0.52941176 0.41176471 0.35294118 0.47058824
 0.23529412 0.82352941 0.23529412 0.23529412 0.         0.29411765
 0.76470588 0.41176471 0.52941176 0.47058824 0.82352941 0.29411765
 0.29411765 0.58823529 0.88235294 0.70588235 0.41176471 0.05882353
 0.29411765 0.52941176 0.76470588 0.76470588 0.47058824 0.64705882
 0.41176471 0.70588235 0.58823529 0.29411765 0.41176471 0.52941176
 0.64705882 0.47058824 0.17647059 0.35294118 0.64705882 0.64705882
 0.64705882 0.76470588 0.88235294 0.11764706 0.64705882 0.41176471
 0.76470588 0.23529412 0.58823529 0.94117647 0.58823529 0.29411765
 0.47058824 0.52941176 0.17647059 0.82352941 0.76470588 0.58823529
 0.23529412 0.47058824 0.76470588 0.64705882 0.11764706 0.70588235
 0.94117647 0.47058824 0.70588235 0.11764706 1.         0.35294118
 0.76470588 0.11764706 0.64705882 0.17647059 0.41176471 0.64705882
 0.29411765 0.47058824 0.05882353 0.70588235 0.41176471 0.47058824
 0.05882353 0.23529412 0.05882353 0.58823529 0.82352941 0.70588235
 0.52941176 0.70588235 0.52941176 0.64705882 0.17647059 0.64705882
 0.35294118 0.23529412 0.35294118 0.52941176 0.82352941 0.52941176
 0.58823529 0.70588235 0.82352941 0.41176471 0.29411765 0.94117647
 0.52941176 0.58823529 0.58823529 0.11764706 0.88235294 0.05882353
 0.35294118 0.70588235 1.         0.05882353 0.05882353 0.
 0.47058824 0.70588235 0.94117647 0.41176471 0.76470588 0.29411765
 0.         0.47058824 0.76470588 0.52941176 0.52941176 0.47058824
 0.52941176 0.23529412 0.88235294 0.58823529 0.64705882 0.76470588
 0.17647059 0.41176471 0.41176471 0.64705882 0.23529412 0.64705882
 0.58823529 0.94117647 0.23529412 0.17647059 0.64705882 0.47058824
 0.70588235 0.23529412 0.88235294 0.35294118 0.47058824 0.94117647
 0.23529412 0.52941176 0.35294118 0.47058824 0.52941176 0.88235294
 0.52941176 0.23529412 0.05882353 0.47058824 0.70588235 0.82352941
 0.82352941 0.35294118 0.58823529 0.82352941 0.35294118 0.17647059
 0.11764706 0.64705882 0.70588235 0.23529412 0.88235294 0.64705882
 0.88235294 0.64705882 0.88235294 0.64705882 0.11764706 0.35294118
 0.41176471 0.52941176 0.64705882 0.82352941 0.11764706 0.11764706
 0.82352941 0.64705882 0.76470588 0.29411765 0.76470588 0.58823529
 0.76470588 0.47058824 0.41176471 0.05882353 0.17647059 0.29411765
 0.64705882 0.29411765 0.47058824 0.29411765 0.23529412 0.29411765
 0.29411765 0.17647059 0.64705882 0.47058824 0.47058824 0.70588235
 0.82352941 0.70588235 0.17647059 0.82352941 0.64705882 0.29411765
 0.11764706 0.35294118 0.47058824 0.58823529 0.35294118 0.47058824
 0.17647059 0.47058824 0.17647059 0.94117647 0.64705882 0.58823529
 0.76470588 0.70588235 0.17647059 0.88235294 0.05882353 0.64705882
 0.94117647 0.23529412 0.29411765 0.17647059 0.         0.52941176
 0.29411765 0.52941176 0.88235294 0.52941176 0.23529412 0.47058824
 0.47058824 0.82352941 0.94117647 0.29411765 0.76470588 0.58823529
 0.41176471 0.58823529 0.94117647 0.23529412 0.29411765 0.76470588
 0.23529412 0.64705882 0.23529412 0.88235294 0.11764706 0.70588235
 0.82352941 0.23529412 0.17647059 0.64705882 0.11764706 0.76470588
 0.94117647 0.         0.35294118 0.82352941 0.23529412 0.76470588
 0.41176471 0.41176471 1.         0.64705882 0.11764706 0.70588235
 0.82352941 0.64705882 0.82352941 0.82352941 0.52941176 0.70588235
 0.58823529 0.76470588 0.52941176 0.58823529 0.64705882 0.52941176
 0.23529412 0.47058824 0.88235294 0.29411765 0.88235294 0.64705882
 0.35294118 0.41176471 0.70588235 0.11764706 0.23529412 0.70588235
 0.23529412 0.58823529 0.47058824 0.41176471 0.64705882 0.41176471
 0.11764706 0.52941176 0.76470588 0.35294118 0.64705882 0.23529412
 0.52941176 0.64705882 0.94117647 0.76470588 0.76470588 0.23529412
 0.17647059 0.29411765 0.82352941 0.35294118 0.88235294 0.58823529
 0.58823529 0.64705882 0.17647059 0.11764706 0.52941176 0.35294118
 0.70588235 0.47058824 0.05882353 0.70588235 0.17647059 0.17647059
 0.35294118 0.17647059 0.47058824 0.70588235 0.17647059 0.17647059
 0.76470588 0.29411765 0.47058824 0.11764706 0.52941176 0.47058824
 0.35294118 0.35294118 0.29411765 0.58823529 0.41176471 0.70588235
 0.41176471 0.47058824 0.70588235 0.58823529 0.23529412 0.17647059
 0.52941176 0.41176471 0.23529412 0.17647059 0.41176471 0.76470588
 0.88235294 0.70588235 0.17647059 0.41176471 0.35294118 0.88235294
 0.47058824 0.11764706 0.70588235 0.35294118 0.70588235 0.35294118
 0.82352941 0.41176471 0.41176471 0.35294118 0.41176471 0.23529412
 0.52941176 0.35294118 0.82352941 0.52941176 0.35294118 0.64705882
 0.35294118 0.58823529 0.70588235 0.23529412 0.17647059 0.76470588
 0.41176471 0.64705882 0.47058824 0.52941176 0.88235294 0.64705882
 0.76470588 0.58823529 0.70588235 0.82352941 0.94117647 0.52941176
 0.41176471 0.82352941 0.82352941 0.35294118 0.94117647 0.47058824
 0.82352941 0.76470588 0.70588235 0.58823529 0.41176471 0.35294118
 0.11764706 0.76470588 0.70588235 0.58823529 0.29411765 0.35294118
 0.29411765 0.47058824 0.35294118 0.11764706 0.41176471 0.70588235
 0.76470588 0.58823529 0.64705882 0.70588235 0.35294118 0.52941176
 0.58823529 0.94117647 0.35294118 0.23529412 0.94117647 0.11764706
 0.35294118 0.52941176 0.76470588 0.94117647 0.88235294 0.88235294
 0.82352941 0.94117647 0.58823529 0.82352941 0.70588235 0.41176471
 0.88235294 0.58823529 0.23529412 0.23529412 0.29411765 0.41176471
 0.82352941 0.88235294 0.29411765 0.29411765 0.05882353 0.94117647
 0.88235294 0.29411765 0.23529412 0.41176471 0.88235294 0.29411765
 0.64705882 0.76470588 0.47058824 0.52941176 0.29411765 0.64705882
 0.64705882 0.35294118 0.58823529 0.05882353 0.52941176 0.70588235
 1.         0.70588235 0.52941176 0.29411765 0.17647059 0.41176471
 0.29411765 0.88235294 0.47058824 0.70588235 0.82352941 0.70588235
 0.47058824 0.58823529 0.52941176 0.41176471 0.29411765 0.76470588
 0.35294118 0.         0.29411765 0.52941176 0.88235294 0.29411765
 0.17647059 0.11764706 0.82352941 0.23529412 0.82352941 0.70588235
 0.52941176 0.82352941 0.41176471 0.17647059 0.88235294 0.64705882
 0.52941176 0.05882353 0.76470588 0.17647059 0.88235294 0.52941176
 0.82352941 0.76470588 0.35294118 0.41176471 0.70588235 0.47058824
 0.70588235 0.76470588 0.47058824 0.64705882 0.76470588 0.58823529
 0.47058824 0.58823529 0.70588235 0.70588235 0.70588235 0.94117647
 0.94117647 0.29411765 0.76470588 0.64705882 0.47058824 0.70588235
 0.58823529 0.76470588 0.35294118 0.17647059 0.70588235 0.47058824
 0.58823529 0.58823529 0.41176471 0.64705882 0.47058824 0.35294118
 0.05882353 0.41176471 0.11764706 0.35294118 0.41176471 0.47058824
 0.29411765 0.94117647 0.58823529 0.23529412 0.58823529 0.58823529
 0.41176471 0.23529412 0.52941176 0.52941176 0.76470588 0.76470588
 0.58823529 0.70588235 0.47058824 0.35294118 0.88235294 0.52941176
 0.70588235 0.47058824 0.29411765 0.47058824 0.05882353 0.23529412
 0.88235294 0.17647059 0.29411765 0.88235294 0.29411765 0.58823529
 0.47058824 0.35294118 0.29411765 0.17647059 0.17647059 0.35294118
 0.88235294 0.52941176 0.41176471 0.58823529 0.29411765 0.64705882
 0.35294118 0.64705882 0.52941176 0.58823529 0.94117647 0.94117647
 0.58823529 0.58823529 0.76470588 0.82352941 0.29411765 0.05882353
 0.64705882 0.29411765 0.11764706 0.35294118 0.52941176 0.70588235
 0.76470588 0.47058824 0.41176471 0.88235294 0.64705882 0.17647059
 0.23529412 0.82352941 0.17647059 0.11764706 0.41176471 0.11764706
 0.         0.29411765 0.35294118 0.76470588 0.17647059 0.41176471
 0.58823529 0.88235294 0.23529412 0.82352941 0.52941176 0.23529412
 0.35294118 0.11764706 0.58823529 0.11764706 0.41176471 0.29411765
 0.41176471 0.76470588 0.47058824 0.11764706 0.17647059 0.82352941
 0.76470588 0.76470588 0.64705882 0.23529412 0.58823529 0.23529412
 0.82352941 0.88235294 0.41176471 0.76470588 0.35294118 0.64705882
 0.94117647 0.94117647 0.35294118 0.94117647 0.17647059 0.35294118
 0.23529412 0.64705882 0.58823529 0.05882353 0.52941176 0.35294118
 0.11764706 0.64705882 0.41176471 0.29411765 0.88235294 0.29411765
 0.52941176 0.35294118 0.52941176 0.29411765 0.41176471 0.76470588
 0.58823529 0.41176471 0.35294118 0.47058824 0.76470588 0.82352941
 0.52941176 0.82352941 0.94117647 0.52941176 0.29411765 0.52941176
 0.23529412 0.05882353 0.35294118 0.64705882 0.58823529 0.70588235
 0.76470588 0.82352941 0.70588235 0.58823529 0.82352941 0.05882353
 0.82352941 0.82352941 0.88235294 0.76470588 0.82352941 0.17647059
 0.23529412 0.23529412 0.29411765 0.29411765 0.35294118 0.41176471
 0.70588235 0.70588235 0.35294118 0.41176471 0.47058824 1.
 1.         0.82352941 0.88235294 0.76470588]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  adf.loc[:, ["x"]] = (adf["x"] - adf["x"].min()) / (adf["x"].max() - adf["x"].min())
C:\Users\44745\AppData\Local\Temp\ipykernel_220664\1428150344.py:8: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.71186441 0.52542373 0.28813559 0.13559322 0.76271186 0.42372881
 0.38983051 0.93220339 0.6440678  0.23728814 0.25423729 0.6440678
 0.05084746 0.03389831 0.44067797 0.22033898 0.40677966 0.22033898
 0.77966102 0.30508475 0.81355932 0.54237288 0.22033898 0.3220339
 0.54237288 0.44067797 0.06779661 0.59322034 0.44067797 0.76271186
 0.76271186 0.69491525 0.79661017 0.79661017 0.08474576 0.62711864
 0.57627119 0.45762712 0.83050847 0.38983051 0.96610169 0.72881356
 0.79661017 0.3220339  0.47457627 0.74576271 0.47457627 0.11864407
 0.42372881 0.84745763 0.16949153 0.11864407 0.72881356 0.54237288
 0.30508475 0.27118644 0.30508475 0.69491525 0.52542373 0.62711864
 0.42372881 0.         0.69491525 0.10169492 0.96610169 0.74576271
 0.27118644 0.76271186 0.62711864 0.84745763 0.44067797 0.01694915
 0.52542373 0.33898305 0.72881356 0.42372881 0.40677966 0.83050847
 0.50847458 0.71186441 0.45762712 0.61016949 0.13559322 0.69491525
 0.11864407 0.37288136 0.6779661  0.55932203 0.16949153 0.57627119
 0.59322034 0.6440678  0.54237288 0.79661017 0.13559322 0.3220339
 0.52542373 0.28813559 0.74576271 0.3220339  0.59322034 0.71186441
 0.6440678  0.03389831 0.86440678 0.6779661  0.45762712 0.28813559
 0.40677966 0.49152542 0.08474576 0.50847458 0.55932203 0.27118644
 0.52542373 0.3559322  0.45762712 0.50847458 0.59322034 0.47457627
 0.55932203 0.6440678  0.66101695 0.37288136 0.6440678  0.6779661
 0.74576271 0.11864407 0.27118644 0.69491525 0.83050847 0.55932203
 0.83050847 0.18644068 0.11864407 0.54237288 0.37288136 0.94915254
 0.25423729 0.62711864 0.10169492 0.18644068 0.76271186 0.30508475
 0.55932203 0.38983051 0.84745763 0.30508475 0.25423729 0.57627119
 0.25423729 0.23728814 0.49152542 0.49152542 0.71186441 0.50847458
 0.37288136 0.40677966 0.61016949 0.83050847 0.25423729 0.45762712
 0.61016949 0.45762712 0.76271186 0.79661017 0.20338983 0.77966102
 0.18644068 0.50847458 0.15254237 0.86440678 0.06779661 0.23728814
 0.37288136 0.71186441 0.47457627 0.6779661  0.22033898 0.03389831
 0.42372881 0.3220339  0.23728814 0.40677966 0.30508475 0.93220339
 0.84745763 0.77966102 0.71186441 0.40677966 0.30508475 0.66101695
 0.55932203 0.40677966 0.47457627 0.62711864 0.15254237 0.52542373
 0.28813559 0.69491525 0.6440678  0.94915254 0.47457627 0.45762712
 0.38983051 0.57627119 0.98305085 0.13559322 0.3559322  0.62711864
 0.47457627 0.22033898 0.42372881 0.54237288 0.61016949 0.81355932
 0.74576271 0.66101695 0.42372881 0.38983051 0.54237288 0.93220339
 0.93220339 0.57627119 0.05084746 0.81355932 0.57627119 0.50847458
 0.52542373 0.6440678  0.28813559 0.71186441 0.27118644 0.54237288
 0.6779661  0.55932203 0.94915254 0.44067797 0.59322034 0.44067797
 0.20338983 0.59322034 0.13559322 0.28813559 0.44067797 0.74576271
 0.23728814 0.49152542 0.28813559 0.50847458 0.25423729 0.88135593
 0.76271186 0.08474576 0.27118644 0.15254237 0.84745763 0.20338983
 0.40677966 0.81355932 0.71186441 0.30508475 0.55932203 0.38983051
 0.47457627 0.06779661 0.52542373 0.38983051 0.16949153 0.3559322
 0.59322034 0.45762712 0.88135593 0.55932203 0.47457627 0.54237288
 0.44067797 0.66101695 0.62711864 0.25423729 0.52542373 0.93220339
 0.55932203 0.91525424 0.18644068 0.08474576 0.71186441 1.
 0.6779661  0.08474576 0.52542373 0.79661017 0.20338983 0.15254237
 0.98305085 0.18644068 0.33898305 0.57627119 0.69491525 0.18644068
 0.76271186 0.77966102 0.86440678 0.57627119 0.55932203 0.61016949
 0.06779661 0.62711864 0.69491525 0.86440678 0.74576271 0.37288136
 0.54237288 0.57627119 0.38983051 0.42372881 0.42372881 0.16949153
 0.57627119 0.40677966 0.55932203 0.93220339 0.27118644 0.89830508
 0.50847458 0.76271186 0.54237288 0.33898305 0.89830508 0.54237288
 0.23728814 0.05084746 0.13559322 0.05084746 0.62711864 0.88135593
 0.38983051 0.49152542 0.6779661  0.77966102 0.20338983 0.23728814
 0.94915254 0.23728814 0.28813559 0.33898305 0.27118644 0.72881356
 0.25423729 0.74576271 0.20338983 0.96610169 0.89830508 0.05084746
 0.38983051 0.86440678 0.77966102 0.77966102 0.88135593 0.81355932
 0.37288136 0.15254237 0.42372881 0.55932203 0.61016949 0.15254237
 0.23728814 0.15254237 0.40677966 0.84745763 0.40677966 0.45762712
 0.13559322 0.71186441 0.61016949 0.3220339  0.61016949 0.79661017
 0.20338983 0.98305085 0.33898305 0.38983051 0.6779661  0.45762712
 0.18644068 0.81355932 0.23728814 0.81355932 0.22033898 0.33898305
 0.44067797 0.61016949 0.86440678 0.3559322  0.11864407 0.66101695
 0.16949153 0.86440678 0.08474576 0.         0.16949153 0.93220339
 0.28813559 0.83050847 0.66101695 0.06779661 0.3220339  0.42372881
 0.44067797 0.45762712 0.16949153 0.84745763 0.37288136 0.84745763
 0.69491525 0.3559322  0.3220339  0.74576271 0.30508475 0.44067797
 0.69491525 0.42372881 0.18644068 0.45762712 0.83050847 0.49152542
 0.18644068 0.88135593 0.72881356 0.37288136 0.3220339  0.61016949
 0.3559322  0.61016949 0.20338983 0.23728814 0.69491525 0.94915254
 0.33898305 0.88135593 0.22033898 0.91525424 0.55932203 0.3220339
 0.62711864 0.25423729 0.52542373 1.         0.22033898 0.33898305
 0.83050847 0.33898305 0.91525424 0.28813559 0.37288136 0.84745763
 0.77966102 0.49152542 0.44067797 0.15254237 0.40677966 0.79661017
 0.77966102 0.49152542 0.49152542 0.72881356 0.15254237 0.6779661
 0.71186441 0.33898305 0.05084746 0.91525424 0.88135593 0.20338983
 0.47457627 0.74576271 0.52542373 0.76271186 0.66101695 0.16949153
 0.3559322  0.77966102 0.37288136 0.33898305 0.44067797 0.50847458
 0.47457627 0.57627119 0.66101695 0.59322034 0.47457627 0.45762712
 0.88135593 0.98305085 0.57627119 0.62711864 0.50847458 0.66101695
 0.66101695 0.3559322  0.52542373 0.62711864 0.77966102 0.6440678
 0.11864407 0.28813559 0.28813559 0.6779661  0.66101695 0.6779661
 0.30508475 0.49152542 0.27118644 0.3220339  0.37288136 0.18644068
 0.54237288 0.86440678 0.40677966 0.11864407 0.33898305 0.49152542
 0.72881356 0.15254237 0.15254237 0.3220339  0.3559322  0.61016949
 0.45762712 0.27118644 0.49152542 0.61016949 0.22033898 0.52542373
 0.42372881 0.55932203 0.10169492 0.50847458 0.74576271 0.33898305
 0.72881356 0.27118644 0.42372881 0.27118644 0.6779661  0.59322034
 0.84745763 0.22033898 0.33898305 0.54237288 0.33898305 0.47457627
 0.76271186 0.44067797 0.6440678  0.66101695 0.3220339  0.13559322
 0.86440678 0.72881356 0.61016949 0.45762712 0.27118644 0.10169492
 0.05084746 0.3559322  0.86440678 0.3559322  0.59322034 0.91525424
 0.25423729 0.54237288 0.72881356 0.57627119 0.6440678  0.96610169
 0.25423729 0.30508475 0.3220339  0.10169492 0.6440678  0.88135593
 0.06779661 0.88135593 0.10169492 0.79661017 0.86440678 0.55932203
 0.40677966 0.6440678  0.44067797 0.01694915 0.25423729 0.22033898
 0.28813559 0.22033898 0.50847458 0.18644068 0.6440678  0.3220339
 0.76271186 0.45762712 0.10169492 0.20338983 0.74576271 0.16949153
 0.79661017 0.66101695 0.49152542 0.10169492 0.18644068 0.05084746
 0.42372881 0.3559322  0.37288136 0.74576271 0.20338983 0.89830508
 0.16949153 0.50847458 0.89830508 0.83050847 0.71186441 0.20338983
 0.89830508 0.3559322  0.47457627 0.49152542 0.89830508 0.62711864
 0.93220339 0.15254237 0.08474576 0.23728814 0.38983051 0.59322034
 0.13559322 0.61016949 0.81355932 0.22033898 0.40677966 0.30508475
 0.72881356 0.79661017 0.94915254 0.77966102 0.37288136 0.61016949
 0.57627119 0.06779661 0.40677966 0.30508475 0.28813559 0.62711864
 0.47457627 0.30508475 0.06779661 0.83050847 0.38983051 0.96610169
 0.72881356 0.47457627 0.62711864 0.03389831 0.45762712 0.27118644
 0.01694915 0.81355932 0.22033898 0.57627119 0.10169492 0.6779661
 0.57627119 0.25423729 0.81355932 0.13559322 0.6779661  0.37288136
 0.79661017 0.91525424 0.13559322 0.3559322  0.59322034 0.77966102
 0.33898305 0.11864407 0.44067797 0.66101695 0.79661017 0.44067797
 0.55932203 0.89830508 0.91525424 0.54237288 0.66101695 0.76271186
 0.11864407 0.37288136 0.49152542 0.74576271 0.42372881 0.88135593
 0.50847458 0.62711864 0.50847458 0.28813559 0.91525424 0.06779661
 0.08474576 0.06779661 0.81355932 0.69491525 0.76271186 0.69491525
 0.66101695 0.38983051 0.11864407 0.89830508 0.94915254 0.84745763
 0.71186441 0.23728814 0.30508475 0.52542373 0.08474576 0.01694915
 0.59322034 0.69491525 0.98305085 0.49152542 0.6440678  0.59322034
 0.20338983 0.49152542 0.10169492 0.50847458 0.81355932 0.71186441
 0.52542373 0.3559322  0.25423729 0.6779661  0.16949153 0.91525424
 0.71186441 0.54237288 0.52542373 0.83050847 0.50847458 0.08474576
 0.59322034 0.61016949 0.89830508 0.27118644 0.81355932 0.83050847
 0.38983051 0.47457627 0.72881356 0.77966102 0.18644068 0.72881356
 0.72881356 0.38983051 0.6440678  0.42372881 0.96610169 0.57627119
 0.03389831 0.55932203 0.03389831 0.69491525 0.16949153 0.59322034
 0.86440678 0.84745763 0.83050847 0.91525424 0.89830508 0.91525424
 0.93220339 0.94915254 0.96610169 0.98305085 1.         1.
 0.96610169 0.94915254 0.03389831 0.03389831 0.01694915 0.52542373
 0.38983051 0.05084746 0.13559322 0.93220339]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  adf.loc[:, ["y"]] = (adf["y"] - adf["y"].min()) / (adf["y"].max() - adf["y"].min())
C:\Users\44745\AppData\Local\Temp\ipykernel_220664\1428150344.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.83333333 0.75       0.16666667 0.33333333 0.75       0.5
 0.58333333 0.97222222 0.5        0.13888889 0.11111111 0.80555556
 0.16666667 0.11111111 0.38888889 0.33333333 0.38888889 0.13888889
 0.91666667 0.25       0.80555556 0.55555556 0.36111111 0.38888889
 0.77777778 0.41666667 0.13888889 0.44444444 0.47222222 0.55555556
 0.72222222 0.66666667 0.66666667 0.58333333 0.13888889 0.44444444
 0.52777778 0.47222222 0.77777778 0.47222222 0.97222222 0.72222222
 0.88888889 0.22222222 0.61111111 0.83333333 0.72222222 0.30555556
 0.33333333 0.83333333 0.22222222 0.22222222 0.55555556 0.63888889
 0.44444444 0.27777778 0.16666667 0.58333333 0.58333333 0.83333333
 0.55555556 0.08333333 0.55555556 0.05555556 0.91666667 0.63888889
 0.36111111 0.63888889 0.58333333 0.88888889 0.5        0.11111111
 0.47222222 0.38888889 0.86111111 0.52777778 0.36111111 0.72222222
 0.44444444 0.55555556 0.30555556 0.77777778 0.13888889 0.72222222
 0.08333333 0.52777778 0.61111111 0.36111111 0.19444444 0.66666667
 0.61111111 0.61111111 0.69444444 0.61111111 0.08333333 0.33333333
 0.66666667 0.36111111 0.58333333 0.30555556 0.77777778 0.58333333
 0.41666667 0.13888889 0.72222222 0.83333333 0.25       0.41666667
 0.30555556 0.69444444 0.11111111 0.66666667 0.61111111 0.25
 0.63888889 0.41666667 0.69444444 0.41666667 0.63888889 0.5

https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22%3A%20%7B%22x%22%3A%20%5B1e-09%2C%20%22m%22%5D%2C%20%22y%22%3A%20%5B1e-09%2C%20%22m%22%5D%2C%20%22z%22%3A%20%5B1e-09%2C%20%22m%22%5D%7D%2C%20%22layers%22%3A%20%5B%7B%22name%22%3A%20%22x%20%22%2C%20%22segmentColors%22%3A%20%7B%22720575940603042272%22%3A%20%22%23433d84%22%2C%20%22720575940603200428%22%3A%20%22%23481769%22%2C%20%22720575940603327916%22%3A%20%22%23b0dd2f%22%2C%20%22720575940603935334%22%3A%20%22%233d4e8a%22%2C%20%22720575940604151008%22%3A%20%22%23297b8e%22%2C%20%22720575940604191456%22%3A%20%22%23433d84%22%2C%20%22720575940604255712%22%3A%20%22%23355e8d%22%2C%20%22720575940604508332%22%3A%20%22%2365cb5e%22%2C%20%22720575940604607678%22%3A%20%22%2389d548%22%2C%20%22720575940604687532%22%3A%20%22%2389d548%22%2C%20%22720575940604714929%22%3A%20%22%23d8e219%22%2C%20%22720575940604947657%22%3A%20%22%23472a7a%22%2C%20%22720575940605029856%22%3A%20%22%2323898e%22%2C%20%22720575940605215665%22%3A%20%22%232eb37c%22%2C%20%22720575940605262880%22%3A%20%22%23297b8e%22%2C%20%22720575940605478321%22%3A%20%22%2389d548%22%2C%20%22720575940605581024%22%3A%20%22%2365cb5e%22%2C%20%22720575940605668128%22%3A%20%22%233d4e8a%22%2C%20%22720575940606042814%22%3A%20%22%23472a7a%22%2C%20%22720575940606057900%22%3A%20%22%2389d548%22%2C%20%22720575940606333385%22%3A%20%22%23297b8e%22%2C%20%22720575940606398240%22%3A%20%22%231f978b%22%2C%20%22720575940606476478%22%3A%20%22%233d4e8a%22%2C%20%22720575940606513342%22%3A%20%22%2321a585%22%2C%20%22720575940606654386%22%3A%20%22%2323898e%22%2C%20%22720575940606665564%22%3A%20%22%232e6d8e%22%2C%20%22720575940606712777%22%3A%20%22%2323898e%22%2C%20%22720575940606944898%22%3A%20%22%2321a585%22%2C%20%22720575940607228629%22%3A%20%22%23433d84%22%2C%20%22720575940607385283%22%3A%20%22%2389d548%22%2C%20%22720575940607730780%22%3A%20%22%2323898e%22%2C%20%22720575940607787138%22%3A%20%22%23b0dd2f%22%2C%20%22720575940608157635%22%3A%20%22%231f978b%22%2C%20%22720575940608211780%22%3A%20%22%231f978b%22%2C%20%22720575940608278281%22%3A%20%22%2346c06f%22%2C%20%22720575940608309771%22%3A%20%22%23b0dd2f%22%2C%20%22720575940608431061%22%3A%20%22%23b0dd2f%22%2C%20%22720575940608553155%22%3A%20%22%2321a585%22%2C%20%22720575940608810798%22%3A%20%22%231f978b%22%2C%20%22720575940608927534%22%3A%20%22%231f978b%22%2C%20%22720575940609063800%22%3A%20%22%23297b8e%22%2C%20%22720575940609312860%22%3A%20%22%232e6d8e%22%2C%20%22720575940609453010%22%3A%20%22%2323898e%22%2C%20%22720575940609463620%22%3A%20%22%233d4e8a%22%2C%20%22720575940609555406%22%3A%20%22%2389d548%22%2C%20%22720575940609667083%22%3A%20%22%232eb37c%22%2C%20%22720575940609758217%22%3A%20%22%232eb37c%22%2C%20%22720575940609925589%22%3A%20%22%233d4e8a%22%2C%20%22720575940610007598%22%3A%20%22%233d4e8a%22%2C%20%22720575940610177941%22%3A%20%22%233d4e8a%22%2C%20%22720575940610277956%22%3A%20%22%23355e8d%22%2C%20%22720575940610316664%22%3A%20%22%2365cb5e%22%2C%20%22720575940610418296%22%3A%20%22%23297b8e%22%2C%20%22720575940610438898%22%3A%20%22%2323898e%22%2C%20%22720575940610460402%22%3A%20%22%2389d548%22%2C%20%22720575940610533582%22%3A%20%22%23355e8d%22%2C%20%22720575940610578786%22%3A%20%22%2321a585%22%2C%20%22720575940610580578%22%3A%20%22%23b0dd2f%22%2C%20%22720575940610674090%22%3A%20%22%2346c06f%22%2C%20%22720575940610695338%22%3A%20%22%23297b8e%22%2C%20%22720575940610739882%22%3A%20%22%23481769%22%2C%20%22720575940610740394%22%3A%20%22%23355e8d%22%2C%20%22720575940610772174%22%3A%20%22%2365cb5e%22%2C%20%22720575940610903854%22%3A%20%22%2365cb5e%22%2C%20%22720575940610934340%22%3A%20%22%2365cb5e%22%2C%20%22720575940610952198%22%3A%20%22%232eb37c%22%2C%20%22720575940610952982%22%3A%20%22%23297b8e%22%2C%20%22720575940610953478%22%3A%20%22%2346c06f%22%2C%20%22720575940610979590%22%3A%20%22%2321a585%22%2C%20%22720575940611054798%22%3A%20%22%23355e8d%22%2C%20%22720575940611126648%22%3A%20%22%23297b8e%22%2C%20%22720575940611216867%22%3A%20%22%2323898e%22%2C%20%22720575940611352469%22%3A%20%22%23433d84%22%2C%20%22720575940611361378%22%3A%20%22%232e6d8e%22%2C%20%22720575940611362965%22%3A%20%22%232eb37c%22%2C%20%22720575940611489746%22%3A%20%22%232eb37c%22%2C%20%22720575940611524835%22%3A%20%22%2365cb5e%22%2C%20%22720575940611551857%22%3A%20%22%23b0dd2f%22%2C%20%22720575940611625238%22%3A%20%22%23472a7a%22%2C%20%22720575940611667154%22%3A%20%22%2321a585%22%2C%20%22720575940611685489%22%3A%20%22%232eb37c%22%2C%20%22720575940611686513%22%3A%20%22%23297b8e%22%2C%20%22720575940611704689%22%3A%20%22%2365cb5e%22%2C%20%22720575940611751347%22%3A%20%22%233d4e8a%22%2C%20%22720575940611778290%22%3A%20%22%2321a585%22%2C%20%22720575940611780450%22%3A%20%22%23d8e219%22%2C%20%22720575940611838577%22%3A%20%22%2321a585%22%2C%20%22720575940611882725%22%3A%20%22%23355e8d%22%2C%20%22720575940611884773%22%3A%20%22%2323898e%22%2C%20%22720575940612031694%22%3A%20%22%231f978b%22%2C%20%22720575940612109619%22%3A%20%22%23433d84%22%2C%20%22720575940612162227%22%3A%20%22%2389d548%22%2C%20%22720575940612197986%22%3A%20%22%2389d548%22%2C%20%22720575940612334810%22%3A%20%22%2365cb5e%22%2C%20%22720575940612352114%22%3A%20%22%2321a585%22%2C%20%22720575940612393000%22%3A%20%22%233d4e8a%22%2C%20%22720575940612410481%22%3A%20%22%2323898e%22%2C%20%22720575940612523669%22%3A%20%22%233d4e8a%22%2C%20%22720575940612556438%22%3A%20%22%2365cb5e%22%2C%20%22720575940612562525%22%3A%20%22%232eb37c%22%2C%20%22720575940612727550%22%3A%20%22%23472a7a%22%2C%20%22720575940612855219%22%3A%20%22%2323898e%22%2C%20%22720575940612944298%22%3A%20%22%2346c06f%22%2C%20%22720575940613073918%22%3A%20%22%23472a7a%22%2C%20%22720575940613102053%22%3A%20%22%23d8e219%22%2C%20%22720575940613120741%22%3A%20%22%2346c06f%22%2C%20%22720575940613127574%22%3A%20%22%23fde725%22%2C%20%22720575940613416744%22%3A%20%22%2365cb5e%22%2C%20%22720575940613508210%22%3A%20%22%2323898e%22%2C%20%22720575940613616559%22%3A%20%22%232eb37c%22%2C%20%22720575940613638290%22%3A%20%22%23433d84%22%2C%20%22720575940613676975%22%3A%20%22%23297b8e%22%2C%20%22720575940613700305%22%3A%20%22%232eb37c%22%2C%20%22720575940613709983%22%3A%20%22%23355e8d%22%2C%20%22720575940613857251%22%3A%20%22%2323898e%22%2C%20%22720575940613919135%22%3A%20%22%23481769%22%2C%20%22720575940613956242%22%3A%20%22%23297b8e%22%2C%20%22720575940613994898%22%3A%20%22%2323898e%22%2C%20%22720575940614026280%22%3A%20%22%2323898e%22%2C%20%22720575940614047500%22%3A%20%22%23481769%22%2C%20%22720575940614104774%22%3A%20%22%233d4e8a%22%2C%20%22720575940614212258%22%3A%20%22%2389d548%22%2C%20%22720575940614282134%22%3A%20%22%2346c06f%22%2C%20%22720575940614448059%22%3A%20%22%231f978b%22%2C%20%22720575940614486782%22%3A%20%22%2346c06f%22%2C%20%22720575940614503285%22%3A%20%22%231f978b%22%2C%20%22720575940614518678%22%3A%20%22%232eb37c%22%2C%20%22720575940614545851%22%3A%20%22%23433d84%22%2C%20%22720575940614570705%22%3A%20%22%232eb37c%22%2C%20%22720575940614607912%22%3A%20%22%2323898e%22%2C%20%22720575940614650163%22%3A%20%22%232e6d8e%22%2C%20%22720575940614750870%22%3A%20%22%232e6d8e%22%2C%20%22720575940614779026%22%3A%20%22%231f978b%22%2C%20%22720575940614850088%22%3A%20%22%2323898e%22%2C%20%22720575940614924946%22%3A%20%22%231f978b%22%2C%20%22720575940614935249%22%3A%20%22%2321a585%22%2C%20%22720575940614968938%22%3A%20%22%2389d548%22%2C%20%22720575940614989107%22%3A%20%22%2365cb5e%22%2C%20%22720575940615088034%22%3A%20%22%23355e8d%22%2C%20%22720575940615240103%22%3A%20%22%23355e8d%22%2C%20%22720575940615261235%22%3A%20%22%23472a7a%22%2C%20%22720575940615266866%22%3A%20%22%231f978b%22%2C%20%22720575940615279419%22%3A%20%22%2321a585%22%2C%20%22720575940615420358%22%3A%20%22%2321a585%22%2C%20%22720575940615590034%22%3A%20%22%233d4e8a%22%2C%20%22720575940615649366%22%3A%20%22%23472a7a%22%2C%20%22720575940615658713%22%3A%20%22%23b0dd2f%22%2C%20%22720575940615702621%22%3A%20%22%23481769%22%2C%20%22720575940615811807%22%3A%20%22%232e6d8e%22%2C%20%22720575940615836450%22%3A%20%22%2346c06f%22%2C%20%22720575940615908353%22%3A%20%22%23fde725%22%2C%20%22720575940615912916%22%3A%20%22%23481769%22%2C%20%22720575940616046348%22%3A%20%22%23fde725%22%2C%20%22720575940616083212%22%3A%20%22%23297b8e%22%2C%20%22720575940616095259%22%3A%20%22%2323898e%22%2C%20%22720575940616097653%22%3A%20%22%2346c06f%22%2C%20%22720575940616111221%22%3A%20%22%23297b8e%22%2C%20%22720575940616168276%22%3A%20%22%23355e8d%22%2C%20%22720575940616304925%22%3A%20%22%2323898e%22%2C%20%22720575940616367133%22%3A%20%22%2365cb5e%22%2C%20%22720575940616496102%22%3A%20%22%231f978b%22%2C%20%22720575940616553541%22%3A%20%22%231f978b%22%2C%20%22720575940616558405%22%3A%20%22%2323898e%22%2C%20%22720575940616572992%22%3A%20%22%231f978b%22%2C%20%22720575940616748096%22%3A%20%22%233d4e8a%22%2C%20%22720575940616787061%22%3A%20%22%23b0dd2f%22%2C%20%22720575940616848140%22%3A%20%22%23d8e219%22%2C%20%22720575940616893638%22%3A%20%22%232e6d8e%22%2C%20%22720575940617027257%22%3A%20%22%2365cb5e%22%2C%20%22720575940617029009%22%3A%20%22%23433d84%22%2C%20%22720575940617037969%22%3A%20%22%23297b8e%22%2C%20%22720575940617076258%22%3A%20%22%23297b8e%22%2C%20%22720575940617213557%22%3A%20%22%233d4e8a%22%2C%20%22720575940617236923%22%3A%20%22%23b0dd2f%22%2C%20%22720575940617246395%22%3A%20%22%232eb37c%22%2C%20%22720575940617264245%22%3A%20%22%231f978b%22%2C%20%22720575940617282747%22%3A%20%22%232eb37c%22%2C%20%22720575940617320331%22%3A%20%22%232eb37c%22%2C%20%22720575940617449506%22%3A%20%22%23d8e219%22%2C%20%22720575940617509716%22%3A%20%22%233d4e8a%22%2C%20%22720575940617578267%22%3A%20%22%23433d84%22%2C%20%22720575940617620509%22%3A%20%22%232eb37c%22%2C%20%22720575940617637204%22%3A%20%22%2323898e%22%2C%20%22720575940617817693%22%3A%20%22%2346c06f%22%2C%20%22720575940617839832%22%3A%20%22%233d4e8a%22%2C%20%22720575940617882342%22%3A%20%22%23b0dd2f%22%2C%20%22720575940618013745%22%3A%20%22%233d4e8a%22%2C%20%22720575940618148766%22%3A%20%22%232e6d8e%22%2C%20%22720575940618156702%22%3A%20%22%2323898e%22%2C%20%22720575940618311892%22%3A%20%22%2389d548%22%2C%20%22720575940618338260%22%3A%20%22%23355e8d%22%2C%20%22720575940618358838%22%3A%20%22%233d4e8a%22%2C%20%22720575940618364325%22%3A%20%22%23481769%22%2C%20%22720575940618389054%22%3A%20%22%2323898e%22%2C%20%22720575940618392157%22%3A%20%22%2321a585%22%2C%20%22720575940618405917%22%3A%20%22%23355e8d%22%2C%20%22720575940618420278%22%3A%20%22%2346c06f%22%2C%20%22720575940618490782%22%3A%20%22%2389d548%22%2C%20%22720575940618491038%22%3A%20%22%2389d548%22%2C%20%22720575940618697506%22%3A%20%22%2321a585%22%2C%20%22720575940618710813%22%3A%20%22%2321a585%22%2C%20%22720575940618728606%22%3A%20%22%2389d548%22%2C%20%22720575940618739136%22%3A%20%22%232e6d8e%22%2C%20%22720575940618786205%22%3A%20%22%232e6d8e%22%2C%20%22720575940618795099%22%3A%20%22%23433d84%22%2C%20%22720575940618826314%22%3A%20%22%23472a7a%22%2C%20%22720575940618860445%22%3A%20%22%23297b8e%22%2C%20%22720575940618902811%22%3A%20%22%2365cb5e%22%2C%20%22720575940618931229%22%3A%20%22%232e6d8e%22%2C%20%22720575940618995028%22%3A%20%22%23d8e219%22%2C%20%22720575940619018779%22%3A%20%22%2365cb5e%22%2C%20%22720575940619121713%22%3A%20%22%2346c06f%22%2C%20%22720575940619213771%22%3A%20%22%233d4e8a%22%2C%20%22720575940619265140%22%3A%20%22%232eb37c%22%2C%20%22720575940619308653%22%3A%20%22%23b0dd2f%22%2C%20%22720575940619333701%22%3A%20%22%23355e8d%22%2C%20%22720575940619393349%22%3A%20%22%23b0dd2f%22%2C%20%22720575940619471440%22%3A%20%22%23b0dd2f%22%2C%20%22720575940619519061%22%3A%20%22%232eb37c%22%2C%20%22720575940619619510%22%3A%20%22%23472a7a%22%2C%20%22720575940619624374%22%3A%20%22%232e6d8e%22%2C%20%22720575940619624630%22%3A%20%22%23297b8e%22%2C%20%22720575940619780731%22%3A%20%22%232eb37c%22%2C%20%22720575940619876890%22%3A%20%22%2389d548%22%2C%20%22720575940619899294%22%3A%20%22%23481769%22%2C%20%22720575940619905919%22%3A%20%22%23472a7a%22%2C%20%22720575940619944360%22%3A%20%22%23472a7a%22%2C%20%22720575940619962422%22%3A%20%22%232eb37c%22%2C%20%22720575940619967435%22%3A%20%22%232eb37c%22%2C%20%22720575940619977087%22%3A%20%22%2365cb5e%22%2C%20%22720575940619997121%22%3A%20%22%23355e8d%22%2C%20%22720575940620101870%22%3A%20%22%2323898e%22%2C%20%22720575940620115541%22%3A%20%22%23297b8e%22%2C%20%22720575940620133243%22%3A%20%22%23fde725%22%2C%20%22720575940620139781%22%3A%20%22%23355e8d%22%2C%20%22720575940620159960%22%3A%20%22%232eb37c%22%2C%20%22720575940620183066%22%3A%20%22%23355e8d%22%2C%20%22720575940620210014%22%3A%20%22%2323898e%22%2C%20%22720575940620233899%22%3A%20%22%23355e8d%22%2C%20%22720575940620298754%22%3A%20%22%233d4e8a%22%2C%20%22720575940620343000%22%3A%20%22%232e6d8e%22%2C%20%22720575940620415568%22%3A%20%22%23355e8d%22%2C%20%22720575940620462177%22%3A%20%22%232eb37c%22%2C%20%22720575940620500801%22%3A%20%22%2323898e%22%2C%20%22720575940620525076%22%3A%20%22%2346c06f%22%2C%20%22720575940620552973%22%3A%20%22%2389d548%22%2C%20%22720575940620605776%22%3A%20%22%23297b8e%22%2C%20%22720575940620655854%22%3A%20%22%2346c06f%22%2C%20%22720575940620728710%22%3A%20%22%23433d84%22%2C%20%22720575940620739494%22%3A%20%22%2389d548%22%2C%20%22720575940620780270%22%3A%20%22%23355e8d%22%2C%20%22720575940620811892%22%3A%20%22%23472a7a%22%2C%20%22720575940620826900%22%3A%20%22%232e6d8e%22%2C%20%22720575940620857776%22%3A%20%22%2323898e%22%2C%20%22720575940620859574%22%3A%20%22%2321a585%22%2C%20%22720575940620916389%22%3A%20%22%232e6d8e%22%2C%20%22720575940620922644%22%3A%20%22%2323898e%22%2C%20%22720575940620941703%22%3A%20%22%2365cb5e%22%2C%20%22720575940620960020%22%3A%20%22%23433d84%22%2C%20%22720575940621003457%22%3A%20%22%23433d84%22%2C%20%22720575940621096686%22%3A%20%22%2323898e%22%2C%20%22720575940621181424%22%3A%20%22%23d8e219%22%2C%20%22720575940621183624%22%3A%20%22%232eb37c%22%2C%20%22720575940621189358%22%3A%20%22%2321a585%22%2C%20%22720575940621194405%22%3A%20%22%2365cb5e%22%2C%20%22720575940621252451%22%3A%20%22%23433d84%22%2C%20%22720575940621263014%22%3A%20%22%23b0dd2f%22%2C%20%22720575940621269603%22%3A%20%22%232eb37c%22%2C%20%22720575940621269696%22%3A%20%22%2365cb5e%22%2C%20%22720575940621304229%22%3A%20%22%23433d84%22%2C%20%22720575940621308912%22%3A%20%22%23355e8d%22%2C%20%22720575940621314440%22%3A%20%22%23433d84%22%2C%20%22720575940621337025%22%3A%20%22%23297b8e%22%2C%20%22720575940621407470%22%3A%20%22%233d4e8a%22%2C%20%22720575940621447350%22%3A%20%22%231f978b%22%2C%20%22720575940621454427%22%3A%20%22%23433d84%22%2C%20%22720575940621472750%22%3A%20%22%23b0dd2f%22%2C%20%22720575940621491226%22%3A%20%22%23355e8d%22%2C%20%22720575940621505718%22%3A%20%22%231f978b%22%2C%20%22720575940621526655%22%3A%20%22%23b0dd2f%22%2C%20%22720575940621528703%22%3A%20%22%231f978b%22%2C%20%22720575940621548543%22%3A%20%22%233d4e8a%22%2C%20%22720575940621585276%22%3A%20%22%2323898e%22%2C%20%22720575940621643132%22%3A%20%22%23d8e219%22%2C%20%22720575940621647996%22%3A%20%22%23355e8d%22%2C%20%22720575940621659046%22%3A%20%22%2346c06f%22%2C%20%22720575940621683973%22%3A%20%22%2365cb5e%22%2C%20%22720575940621699521%22%3A%20%22%233d4e8a%22%2C%20%22720575940621710831%22%3A%20%22%2346c06f%22%2C%20%22720575940621723283%22%3A%20%22%23297b8e%22%2C%20%22720575940621756336%22%3A%20%22%23d8e219%22%2C%20%22720575940621852042%22%3A%20%22%233d4e8a%22%2C%20%22720575940621902674%22%3A%20%22%23355e8d%22%2C%20%22720575940621959185%22%3A%20%22%233d4e8a%22%2C%20%22720575940622000993%22%3A%20%22%233d4e8a%22%2C%20%22720575940622033110%22%3A%20%22%232eb37c%22%2C%20%22720575940622087245%22%3A%20%22%233d4e8a%22%2C%20%22720575940622206442%22%3A%20%22%23472a7a%22%2C%20%22720575940622211241%22%3A%20%22%2389d548%22%2C%20%22720575940622263815%22%3A%20%22%23433d84%22%2C%20%22720575940622286669%22%3A%20%22%23472a7a%22%2C%20%22720575940622304895%22%3A%20%22%2365cb5e%22%2C%20%22720575940622447344%22%3A%20%22%23d8e219%22%2C%20%22720575940622490381%22%3A%20%22%232e6d8e%22%2C%20%22720575940622516104%22%3A%20%22%2389d548%22%2C%20%22720575940622574038%22%3A%20%22%2389d548%22%2C%20%22720575940622617736%22%3A%20%22%2365cb5e%22%2C%20%22720575940622622502%22%3A%20%22%23297b8e%22%2C%20%22720575940622697992%22%3A%20%22%23297b8e%22%2C%20%22720575940622718344%22%3A%20%22%23fde725%22%2C%20%22720575940622747772%22%3A%20%22%232eb37c%22%2C%20%22720575940622780118%22%3A%20%22%2346c06f%22%2C%20%22720575940622821590%22%3A%20%22%233d4e8a%22%2C%20%22720575940622838408%22%3A%20%22%2389d548%22%2C%20%22720575940622864169%22%3A%20%22%232eb37c%22%2C%20%22720575940622893150%22%3A%20%22%231f978b%22%2C%20%22720575940622913285%22%3A%20%22%232eb37c%22%2C%20%22720575940622930019%22%3A%20%22%2389d548%22%2C%20%22720575940622933444%22%3A%20%22%2389d548%22%2C%20%22720575940622954189%22%3A%20%22%231f978b%22%2C%20%22720575940622977791%22%3A%20%22%2321a585%22%2C%20%22720575940623093854%22%3A%20%22%2389d548%22%2C%20%22720575940623160614%22%3A%20%22%231f978b%22%2C%20%22720575940623210933%22%3A%20%22%23b0dd2f%22%2C%20%22720575940623221774%22%3A%20%22%2321a585%22%2C%20%22720575940623328184%22%3A%20%22%231f978b%22%2C%20%22720575940623458428%22%3A%20%22%23fde725%22%2C%20%22720575940623530032%22%3A%20%22%233d4e8a%22%2C%20%22720575940623566472%22%3A%20%22%2323898e%22%2C%20%22720575940623571555%22%3A%20%22%23b0dd2f%22%2C%20%22720575940623604149%22%3A%20%22%23355e8d%22%2C%20%22720575940623627460%22%3A%20%22%23b0dd2f%22%2C%20%22720575940623628105%22%3A%20%22%232eb37c%22%2C%20%22720575940623666320%22%3A%20%22%23297b8e%22%2C%20%22720575940623738365%22%3A%20%22%23472a7a%22%2C%20%22720575940623820523%22%3A%20%22%233d4e8a%22%2C%20%22720575940623877828%22%3A%20%22%2321a585%22%2C%20%22720575940623887128%22%3A%20%22%231f978b%22%2C%20%22720575940623942408%22%3A%20%22%2323898e%22%2C%20%22720575940623946851%22%3A%20%22%2346c06f%22%2C%20%22720575940623948432%22%3A%20%22%23297b8e%22%2C%20%22720575940623989247%22%3A%20%22%2346c06f%22%2C%20%22720575940624086408%22%3A%20%22%2346c06f%22%2C%20%22720575940624121322%22%3A%20%22%23297b8e%22%2C%20%22720575940624136485%22%3A%20%22%23472a7a%22%2C%20%22720575940624161171%22%3A%20%22%2389d548%22%2C%20%22720575940624177900%22%3A%20%22%231f978b%22%2C%20%22720575940624185904%22%3A%20%22%2365cb5e%22%2C%20%22720575940624217528%22%3A%20%22%232e6d8e%22%2C%20%22720575940624234644%22%3A%20%22%232eb37c%22%2C%20%22720575940624292158%22%3A%20%22%233d4e8a%22%2C%20%22720575940624322341%22%3A%20%22%231f978b%22%2C%20%22720575940624328167%22%3A%20%22%232eb37c%22%2C%20%22720575940624335399%22%3A%20%22%23d8e219%22%2C%20%22720575940624374013%22%3A%20%22%233d4e8a%22%2C%20%22720575940624402761%22%3A%20%22%23433d84%22%2C%20%22720575940624467644%22%3A%20%22%2389d548%22%2C%20%22720575940624599836%22%3A%20%22%23b0dd2f%22%2C%20%22720575940624624432%22%3A%20%22%2321a585%22%2C%20%22720575940624654570%22%3A%20%22%2365cb5e%22%2C%20%22720575940624689610%22%3A%20%22%23433d84%22%2C%20%22720575940624733769%22%3A%20%22%23472a7a%22%2C%20%22720575940624769771%22%3A%20%22%231f978b%22%2C%20%22720575940624785934%22%3A%20%22%232e6d8e%22%2C%20%22720575940624864263%22%3A%20%22%2346c06f%22%2C%20%22720575940624940675%22%3A%20%22%2323898e%22%2C%20%22720575940624950676%22%3A%20%22%23481769%22%2C%20%22720575940624951560%22%3A%20%22%2346c06f%22%2C%20%22720575940624959927%22%3A%20%22%2365cb5e%22%2C%20%22720575940625061885%22%3A%20%22%2321a585%22%2C%20%22720575940625153836%22%3A%20%22%23433d84%22%2C%20%22720575940625223954%22%3A%20%22%23433d84%22%2C%20%22720575940625225085%22%3A%20%22%232e6d8e%22%2C%20%22720575940625269822%22%3A%20%22%23433d84%22%2C%20%22720575940625273118%22%3A%20%22%2323898e%22%2C%20%22720575940625276958%22%3A%20%22%2346c06f%22%2C%20%22720575940625303788%22%3A%20%22%2323898e%22%2C%20%22720575940625383944%22%3A%20%22%232eb37c%22%2C%20%22720575940625410441%22%3A%20%22%23433d84%22%2C%20%22720575940625428368%22%3A%20%22%23433d84%22%2C%20%22720575940625448394%22%3A%20%22%2365cb5e%22%2C%20%22720575940625474106%22%3A%20%22%23355e8d%22%2C%20%22720575940625478458%22%3A%20%22%2323898e%22%2C%20%22720575940625483322%22%3A%20%22%23472a7a%22%2C%20%22720575940625496720%22%3A%20%22%231f978b%22%2C%20%22720575940625547909%22%3A%20%22%232e6d8e%22%2C%20%22720575940625568010%22%3A%20

So it seems like q is pointing 60 degrees dorsal, posteriorly; and q is pointing 60 degrees dorsal, anteriorly. x is higher posteriorly. So let's transform p and q into plotting coordinates.

In [6]:
# # Convert axial (p,q) -> Cartesian (x,y)
# def axial_to_xy(p, q):
#     x = 0.5 * (p - q)
#     y = 0.5 * np.sqrt(3) * (p + q)
#     return x, y
# xs, ys = axial_to_xy(vis_cols["p"], vis_cols["q"])

# vis_cols.loc[:, ["x_original"]] = vis_cols["x"]
# vis_cols.loc[:, ["y_original"]] = vis_cols["y"]
# vis_cols.loc[:, ["x"]] = xs
# vis_cols.loc[:, ["y"]] = ys

In [7]:
vis_cols.loc[:, ["x"]] = vis_cols["p"] - vis_cols["q"] + 1
vis_cols.loc[:, ["y"]] = vis_cols["p"] + vis_cols["q"] + 39
vis_cols.loc[:, ["coords"]] = vis_cols[["x", "y"]].apply(
    lambda x: f"{x[0]:.1f},{x[1]:.2f}", axis=1
)
root_to_coords = dict(zip(vis_cols["root_id"], vis_cols["coords"]))
vis_cols

C:\Users\44745\AppData\Local\Temp\ipykernel_220664\2872848241.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  lambda x: f"{x[0]:.1f},{x[1]:.2f}", axis=1

,root_id,hemisphere,type,column_id,x,y,p,q,coords
0,720575940603042272,right,Mi1,1,12,52,12,1,"12.0,52.00"
1,720575940603200428,right,Mi1,2,17,41,9,-7,"17.0,41.00"
2,720575940603327916,right,Mi1,3,-11,27,-12,0,"-11.0,27.00"
3,720575940603935334,right,Mi1,4,10,18,-6,-15,"10.0,18.00"
4,720575940633953965,right,Mi1,5,3,55,9,7,"3.0,55.00"
...,...,...,...,...,...,...,...,...,...
22679,720575940614768179,right,Tm9,791,3,11,-13,-15,"3.0,11.00"
22680,720575940617322101,right,Tm9,792,-15,41,-7,9,"-15.0,41.00"
22681,720575940629639674,right,Tm9,793,-15,33,-11,5,"-15.0,33.00"
22682,720575940634654945,right,Tm9,795,-12,18,-17,-4,"-12.0,18.00"
22683,720575940616321602,right,Tm9,796,-7,65,9,17,"-7.0,65.00"

## make combined cell type

In [8]:
# where are the cell types?
info[["cell_type", "hemibrain_type"]].isna().value_counts()

cell_type  hemibrain_type
False      True              104565
           False              33137
True       True                1542
Name: count, dtype: int64

In [9]:
# around 3k with both cell_type and hemibrain_type - do they correspond to each other?
info[~info.cell_type.isna() & ~info.hemibrain_type.isna()][
    ["cell_type", "hemibrain_type"]
].value_counts()

cell_type  hemibrain_type
KCg-m      KCg-m             2189
KCab       KCab-s             621
           KCab-m             619
           KCab-c             403
LC12       LC12               380
                             ...
CB2778     WEDPN7C              1
SLP398b    SMP365,SMP366        1
PLP024     PLP024               1
CB3889     SMP167               1
CB3088     SLP320               1
Name: count, Length: 4909, dtype: int64

In [10]:
# cell type > hemibrain type > root id
info["combined_type"] = info.cell_type.copy()
info.combined_type.fillna(info.cell_type, inplace=True)
info.combined_type.fillna(info.hemibrain_type, inplace=True)
info.combined_type.fillna(info.root_id.astype(str), inplace=True)

C:\Users\44745\AppData\Local\Temp\ipykernel_220664\4099899446.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  info.combined_type.fillna(info.cell_type, inplace=True)

In [11]:
# make dictionaries to map between columns
typedict = dict(zip(info.root_id, info.combined_type))
sidedict = dict(zip(info.root_id, info.side))
type_super_class_dict = dict(zip(info.combined_type, info.super_class))
type_class_dict = dict(zip(info.combined_type, info.cell_class))
type_sub_class_dict = dict(zip(info.combined_type, info.cell_sub_class))

## read connectivity

In [12]:
# # this can take a minute or two
# from io import BytesIO
# import requests

# # Courtesy of Dr Sven Dorkenwald: https://zenodo.org/records/10676866
# url = "https://zenodo.org/records/10676866/files/proofread_connections_783.feather"
# # Download the file
# response = requests.get(url)
# # Use the file content directly in Python
# file_content = response.content

# conn_full = pd.read_feather(BytesIO(file_content))

# instead, use the new synapses
# downloaded from https://codex.flywire.ai/api/download?dataset=fafb 
conn_full = pd.read_feather(
    "C:\\Users\\44745\\Downloads\\connections_princeton_no_threshold.feather"
)
conn_full.columns = ['pre_pt_root_id', 'post_pt_root_id', 'neuropil','syn_count', 'nt_type']
conn_full

              pre_pt_root_id     post_pt_root_id neuropil  syn_count nt_type
0         720575940625363947  720575940623224444     ME_L         12    GABA
1         720575940613354467  720575940616690107     ME_L          1     ACH
2         720575940630432382  720575940618518557     ME_L         67     ACH
3         720575940627314521  720575940626337738     ME_L         10    GABA
4         720575940616775218  720575940632128018     ME_L          1     ACH
...                      ...                 ...      ...        ...     ...
22285318  720575940651039990  720575940617334745     LO_R          1     ACH
22285319  720575940635618711  720575940641296525    SCL_R          1      DA
22285320  720575940660163969  720575940624087369    SLP_R          2    GLUT
22285321  720575940632648612  720575940626847765      GNG         19    GABA
22285322  720575940627976776  720575940605996209     LO_R          1     ACH

[22285323 rows x 5 columns]

In [13]:
conn_full.loc[:, ["pre_type"]] = conn_full.pre_pt_root_id.map(typedict)
conn_full.loc[:, ["post_type"]] = conn_full.post_pt_root_id.map(typedict)
conn_full.loc[:, ["pre_side"]] = conn_full.pre_pt_root_id.map(sidedict)
conn_full.loc[:, ["post_side"]] = conn_full.post_pt_root_id.map(sidedict)
conn_full.loc[:, ["pre_super_class"]] = conn_full.pre_type.map(type_super_class_dict)
conn_full.loc[:, ["post_super_class"]] = conn_full.post_type.map(type_super_class_dict)
conn_full

,pre_pt_root_id,post_pt_root_id,neuropil,syn_count,nt_type,pre_type,post_type,pre_side,post_side,pre_super_class,post_super_class
0,720575940625363947,720575940623224444,ME_L,12,GABA,Dm6,T1,left,left,optic,optic
1,720575940613354467,720575940616690107,ME_L,1,ACH,L3,Lawf2,left,left,optic,optic
2,720575940630432382,720575940618518557,ME_L,67,ACH,L2,L5,left,left,optic,optic
3,720575940627314521,720575940626337738,ME_L,10,GABA,Tm5c,Tm21,left,left,optic,optic
4,720575940616775218,720575940632128018,ME_L,1,ACH,T2a,Dm3q,left,left,optic,optic
...,...,...,...,...,...,...,...,...,...,...,...
22285318,720575940651039990,720575940617334745,LO_R,1,ACH,Tm2,TmY15,right,right,optic,optic
22285319,720575940635618711,720575940641296525,SCL_R,1,DA,OA-ASM2,CB2193,right,right,central,central
22285320,720575940660163969,720575940624087369,SLP_R,2,GLUT,LHPD4b1a,CB0373,right,right,central,central
22285321,720575940632648612,720575940626847765,GNG,19,GABA,CB0008,CB2353,left,left,central,central
22285322,720575940627976776,720575940605996209,LO_R,1,ACH,Tm2,T5d,right,right,optic,optic

In [14]:
# meta currently missing some ids. Remove those from conn_full for now 
conn_full = conn_full[
    conn_full["pre_pt_root_id"].isin(info.root_id) & conn_full["post_pt_root_id"].isin(info.root_id)
]

In [15]:
allids = set(conn_full.pre_pt_root_id) | set(conn_full.post_pt_root_id)
len(allids)

139093

In [16]:
# check to make sure
meta = info[info.root_id.isin(allids)]

In [17]:
# number of GB
len(allids) ** 2 * 4 / 1e9

77.387450596

### read ad connectivity

In [18]:
ad = pd.read_csv('../data/fafb_all_neuron/fafb_ad_split/ad_el.csv')
# non-split to dendrites
bd = pd.read_csv("../data/fafb_all_neuron/fafb_ad_split/bd_el.csv")
# axon to non-split
ab = pd.read_csv("../data/fafb_all_neuron/fafb_ad_split/ab_el.csv")
# non-split to non-split
bb = pd.read_csv("../data/fafb_all_neuron/fafb_ad_split/bb_el.csv")
adconn = pd.concat([ad, bd, ab, bb])
adconn

                pre_root_id        post_root_id  syn_count
0        720575940610326723  720575940618074369          6
1        720575940610326723  720575940608344706          1
2        720575940610326723  720575940613006614         10
3        720575940610326723  720575940613064371         26
4        720575940610326723  720575940625450317          4
...                     ...                 ...        ...
1201492  720575940622487634  720575940633344337          1
1201493  720575940622487634  720575940635781999          1
1201494  720575940622487634  720575940636340366          1
1201495  720575940622487634  720575940646719779          1
1201496  720575940622487634  720575940647599412          1

[11334363 rows x 3 columns]

In [19]:
allids_ad = set(adconn['pre_root_id']).union(set(adconn['post_root_id']))
len(allids_ad)

138393

In [20]:
# there's one id not in conn_full. Let's remove it for now 
adconn = adconn[adconn['pre_root_id'].isin(allids) & adconn['post_root_id'].isin(allids)]

The number of ids isn't the same. This means that some neurons only have axo-axonic, dendro-axonic, or dendro-dendritic connections. Which ones?

In [21]:
difference = [dif for dif in allids - allids_ad]
not_in_adconn = conn_full[conn_full.pre_pt_root_id.isin(difference)]
not_in_adconn.groupby(["pre_type", "post_type"]).syn_count.sum().sort_values(
    ascending=False
).reset_index()

                pre_type           post_type  syn_count
0       SA_DMT_DMetaN_12              CB0918        622
1        SA_DMT_DMetaN_9              CB0918        330
2                   R1-6                R1-6        322
3         SA_DMT_ADMN_11              CB0091        284
4       SA_DMT_DMetaN_12               DNg10        273
...                  ...                 ...        ...
8808  720575940642624292  720575940628557519          1
8809  720575940642624292              CB0034          1
8810  720575940622385703              CB1479          1
8811  720575940622385703              CB0886          1
8812  720575940602309600  720575940635628516          1

[8813 rows x 3 columns]

In [22]:
not_in_adconn[(not_in_adconn.pre_type == "R1-6") & (not_in_adconn.post_type == "L1-3")]

Empty DataFrame
Columns: [pre_pt_root_id, post_pt_root_id, neuropil, syn_count, nt_type, pre_type, post_type, pre_side, post_side, pre_super_class, post_super_class]
Index: []

720575940631859151 and 720575940624096392 have no outputs.

# NT

In [23]:
meta.top_nt.value_counts(dropna=False)

top_nt
acetylcholine    86149
glutamate        24871
gaba             19166
dopamine          5909
serotonin         2268
NaN                514
octopamine         216
Name: count, dtype: int64

In [24]:
meta.known_nt.unique()

array([nan, 'acetylcholine', 'gaba-negative',
       'DILP2, DILP3, DILP5; dARC1; acetylcholine-negative, glutamate-negative, gaba-negative, serotonin-negative, dopamine-negative, tyramine-negative, octopamine-negative',
       'glutamate', 'glutamate; glutamate',
       'dopamine; dopamine, nitric oxide', 'gaba',
       'acetylcholine; sNPF; acetylcholine, sNPF',
       'acetylcholine, gaba-negative, glutamate-negative, dopamine-negative, serotonin-negative, tyramine-negative, octopamine-negative',
       'glutamate; Dh44, allatostatin-c; gaba-negative', 'tyramine',
       'dopamine',
       'acetylcholine, MIP, gaba-negative, glutamate-negative, dopamine-negative, tyramine-negative, octopamine-negative',
       'acetylcholine, Dh44, tachykinin, space blanket, gaba-negative, glutamate-negative, dopamine-negative, tyramine-negative, octopamine-negative',
       'acetylcholine, Dh44, FMRFa, gaba-negative, glutamate-negative, dopamine-negative, serotonin-negative, tyramine-negative, octopamine-negative; acetylcholine',
       'acetylcholine; gaba-negative', 'Dh44', 'octopamine',
       'allatostatin-c; serotonin',
       'glutamate,  acetylcholine-negative, gaba-negative',
       'acetylcholine; acetylcholine', 'dopamine; dopamine',
       'drosulfakinin',
       'dopamine, serotonin, glutamate-negative, acetylcholine-negative, gaba-negative, tyramine-negative, octopamine-negative; dopamine',
       'acetylcholine, glutamate-negative, gaba-negative, dopamine-negative, serotonin-negative, tyramine-negative, octopamine-negative, neuropeptides-negative',
       'glutamate, Nplp1, acetylcholine-negative, gaba-negative',
       'acetylcholine, allatostatin-a, allatostatin-c, NPF, gaba-negative, glutamate-negative, dopamine-negative, serotonin-negative, tyramine-negative, octopamine-negative',
       'tyramine, MIP, Dh331, acetylcholine-negative, gaba-negative, glutamate-negative, dopamine-negative, serotonin-negative, octopamine-negative',
       'gaba, MIP; acetylcholine-negative',
       'gaba; gaba, acetylcholine-negative, glutamate-negative',
       'gaba, dopamine, acetylcholine-negative, glutamate-negative, serotonin-negative, tyramine-negative, octopamine-negative; gaba',
       'serotonin, space blanket, glutamate-negative, acetylcholine-negative, gaba-negative, dopamine-negative, tyramine-negative, octopamine-negative',
       'allatostatin-a; glutamate',
       'glutamate, Nplp1, acetylcholine-negative, gaba-negative, dopamine-negative, serotonin-negative,  tyramine-negative, octopamine-negative',
       'CCHa1, Dh44, glutamate; glutamate',
       'glutamate, MIP, tachykinin, acetylcholine-negative, gaba-negative, dopamine-negative, serotonin-negative, tyramine-negative, octopamine-negative',
       'glutamate; glutamate; gaba-negative',
       'Dh31; acetylcholine-negative',
       'acetylcholine, space blanket; acetylcholine, space blanket',
       'serotonin; amnesiac; gaba; gaba, serotonin',
       'acetylcholine, serotonin', 'glutamate; gaba-negative',
       'serotonin; serotonin',
       'pdf, dNPF; glycine, acetylcholine-negative; acetylcholine-negative, gaba-negative, glutamate-negative; acetylcholine-negative',
       'glutamate; glutamate, acetylcholine; glutamate, acetylcholine, allatostatin-c, Nplp1, gaba-negative, dopamine-negative, serotonin-negative, tyramine-negative, octopamine-negative',
       'gaba; gaba, Dh31, Nplp1, acetylcholine-negative, glutamate-negative',
       'gaba, acetylcholine-negative, glutamate-negative; gaba',
       'glutamate, acetylcholine-negative, gaba-negative; gaba-negative',
       'corazonin, sNPF',
       'gaba, Dh31, dopamine-negative, acetylcholine-negative, glutamate-negative, serotonin-negative, tyramine-negative, octopamine-negative; gaba',
       'glutamate,  acetylcholine-negative, gaba-negative; glutamate',
       'glutamate; glutamate, acetylcholine; glutamate, acetylcholine',
       'capability',
       'allatostatin-a, allatostatin-c, Dh44; nitric oxide; Dh31; acetylcholine-negative',
       'glutamate, dopamine, serotonin, Dh31, Nplp1, acetylcholine-negative, gaba-negative, tyramine-negative, octopamine-negative; dopamine; glutamate',
       'SIFamide; acetylcholine-negative; glutamate',
       'acetylcholine, gaba-negative, glutamate-negative', 'leucokinin',
       'allatostatin-a',
       'acetylcholine, sNPF, gaba-negative, glutamate-negative, dopamine-negative, serotonin-negative, tyramine-negative, octopamine-negative',
       'glutamate, acetylcholine-negative, gaba-negative', 'hugin, sNPF',
       'acetylcholine, gaba-negative, glutamate-negative, dopamine-negative, serotonin-negative, tyramine-negative, octopamine-negative, neuropeptide-negative',
       'acetylcholine, serotonin, gaba-negative, glutamate-negative, dopamine-negative, tyramine-negative, octopamine-negative',
       'myosuppressin', 'acetylcholine, glutamate',
       'dopamine; dopamine; dopamine, sNPF',
       'acetylcholine, space blanket, gaba-negative, glutamate-negative, dopamine-negative, serotonin-negative, tyramine-negative, octopamine-negative; acetylcholine',
       'ITP, tachykinin, sNPF, leucokinin',
       'octopamine; octopamine, acetylcholine-negative, gaba-negative, glutamate-negative, dopamine-negative, serotonin-negative',
       'FMRFa',
       'acetylcholine, space blanket, glutamate-negative, gaba-negative, dopamine-negative, serotonin-negative, tyramine-negative, octopamine-negative',
       'glutamate, acetylcholine-negative, gaba-negative, dopamine-negative, serotonin-negative, tyramine-negative, octopamine-negative',
       'eclosion hormone; gaba-negative', 'drosulfakinin; drosulfakinin',
       'acetylcholine, gaba-negative, glutamate-negative, dopamine-negative, serotonin-negative, tyramine-negative, octopamine-negative; acetylcholine',
       'acetylcholine, gaba-negative, dopamine-negative, serotonin-negative',
       'acetylcholine, glutamate-negative, gaba-negative', 'gaba; gaba',
       'gaba-negative; tyramine', 'serotonin',
       'acetylcholine, allatostatin-a, gaba-negative, glutamate-negative, dopamine-negative, serotonin-negative, tyramine-negative, octopamine-negative',
       'glutamate,  acetylcholine-negative, gaba-negative, dopamine-negative, serotonin-negative,  tyramine-negative, octopamine-negative',
       'glutamate, acetylcholine-negative, gaba-negative, dopamine-negative, serotonin-negative, tyramine-negative, octopamine-negative; gaba-negative',
       'ITP; acetylcholine; glycine, glutamate-negative',
       'glutamate, myosupressin, acetylcholine-negative, gaba-negative',
       'glutamate,  acetylcholine-negative, gaba-negative, neuropeptides-negative',
       'CCAP, bursicon-negative',
       'glutamate, serotonin, proctolin, acetylcholine-negative, gaba-negative, dopamine-negative, tyramine-negative, octopamine-negative; glutamate',
       'glutamate, tyramine, proctolin, acetylcholine-negative, gaba-negative, dopamine-negative, serotonin-negative, octopamine-negative',
       'glutamate, tyramine',
       'pdf, sNPF; glycine; pdf, sNPF; glycine, glutamate-negative; acetylcholine-negative',
       'acetylcholine-negative, glutamate-negative, gaba-negative, serotonin-negative, dopamine-negative, tyramine-negative, octopamine-negative',
       'glutamate, proctolin, acetylcholine-negative, gaba-negative',
       'eclosion hormone', 'acetylcholine, space blanket',
       'dopamine; glutamate; dopamine, glutamate, acetylcholine-negative, gaba-negative, serotonin-negative, tyramine-negative, octopamine-negative',
       'octopamine; octopamine; glutamate, acetylcholine-negative, gaba-negative, dopamine-negative, serotonin-negative, octopamine-negative',
       'dopamine, glutamate-negative, acetylcholine-negative, gaba-negative, serotonin-negative, tyramine-negative, octopamine-negative; dopamine',
       'glutamate, Dh31, Nplp1, acetylcholine-negative, gaba-negative',
       'dopamine; dopamine; dopamine, nitric oxide',
       'acetylcholine, glutamate; gaba-negative',
       'glutamate,  Nplp1, acetylcholine-negative, gaba-negative',
       'tyramine,  space blanket, acetylcholine-negative, gaba-negative, glutamate-negative, dopamine-negative, serotonin-negative, octopamine-negative',
       'glutamate; allatostatin-c; allatostatin-c; CNMa; Dh31; acetylcholine-negative',
       'glutamate, tachykinin, acetylcholine-negative, gaba-negative; gaba-negative',
       'neuropeptides-negative',
       'acetylcholine, glutamate-negative, gaba-negative; acetylcholine',
       'dopamine, Nplp1, glutamate-negative, acetylcholine-negative, gaba-negative, serotonin-negative, tyramine-negative, octopamine-negative',
       'glutamate, Dh44, myosupressin, acetylcholine-negative, gaba-negative',
       'glutamate, octopamine; octopamine',
       'dNPF; dNPF; acetylcholine-negative', 'glutamate; CNMa; Dh31',
       'gaba, acetylcholine-negative, glutamate-negative',
       'acetylcholine, glutamate, gaba-negative, dopamine-negative, serotonin-negative, tyramine-negative, MIP, octopamine-negative',
       'dopamine; dopamine; gaba', 'acetylcholine; dopamine',
       'dopamine; dopamine; dopamine', 'gaba, acetylcholine',
       'acetylcholine, glutamate, Nplp1, gaba-negative',
       'proctolin, allatostatin-c',
       'natalisin; serotonin, MIP; acetylcholine-negative',
       'acetylcholine, tachykinin, space blanket',
       'dopamine, tyramine, allatostatin-c, Dh44, SIFamide; dopamine',
       'tyramine, serotonin, glutamate, Dh44, proctolin, acetylcholine-negative, gaba-negative, dopamine-negative, octopamine-negative; tyramine',
       'glutamate; MIP; acetylcholine-negative', 'hugin',
       'glutamate, Dh31, acetylcholine-negative, gaba-negative',
       'acetylcholine; Dh44',
       'dopamine, serotonin, glutamate, acetylcholine-negative, gaba-negative, tyramine-negative, octopamine-negative; glutamate',
       'acetylcholine, gaba', 'natalisin',
       'dNPF, Dh44; acetylcholine-negative',
       'serotonin; serotonin, acetylcholine-negative, glutamate-negative, gaba-negative, dopamine-negative, negative, tyramine-negative, octopamine-negative, neuropeptides-negative',
       'glutamate; CNMa; Dh31; acetylcholine-negative', 'CCAP',
       'ITP, dNPF; ITP; acetylcholine-negative',
       'DILP3; octopamine, acetylcholine',
       'acetylcholine; allatostatin-c; trissin; orcokinin', 'IPNamide',
       'acetylcholine, serotonin-negative', 'histamine; Dh44',
       'acetylcholine, sNPF', 'capability; myosupressin',
       'gaba, nitric oxide',
       'acetylcholine-negative, glutamate-negative, gaba-negative, dopamine-negative, serotonin-negative, octopamine-negative',
       'acetylcholine; tachykinin', 'acetylcholine, nitric oxide',
       'glutamate, gaba; glutamate',
       'acetylcholine, nitric oxide, dopamine',
       'gaba, nitric oxide; sNPF', 'gaba; allatostatin-a',
       'histamine; acetylcholine, histamine', 'histamine',
       'glutamate, gaba', 'histamine, acetylcholine'], dtype=object)

There are 'negative's. So we can't use regular expression to extract, until we have removed these.

In [25]:
# get unique "negative" entries
import re 
negatives = [
    ent
    for entry in meta.known_nt[meta.known_nt.notna()]
    for ent in re.split(", |; ", entry)
    if "negative" in ent
]
negatives = set(negatives) - {"negative"}
negatives

{' acetylcholine-negative',
 ' tyramine-negative',
 'acetylcholine-negative',
 'bursicon-negative',
 'dopamine-negative',
 'gaba-negative',
 'glutamate-negative',
 'neuropeptide-negative',
 'neuropeptides-negative',
 'octopamine-negative',
 'serotonin-negative',
 'tyramine-negative'}

In [26]:
# subtract strings in negatives from known_nt entries
meta['known_nt_noneg'] = meta.known_nt.copy()
meta.loc[meta.known_nt.notna(), "known_nt_noneg"] = [
    ", ".join([ent for ent in re.split(", |; ", entry) if ent not in negatives])
    for entry in meta.known_nt[meta.known_nt.notna()]
]

C:\Users\44745\AppData\Local\Temp\ipykernel_220664\401387517.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  meta['known_nt_noneg'] = meta.known_nt.copy()

In [27]:
# known_nt takes priority
meta.loc[:, ["known_nt_simplified"]] = meta.known_nt_noneg
# pattern matching: only keep if value contains 'glutamate', 'gaba', or 'acetylcholine'
meta.loc[:, ["known_nt_simplified"]] = meta.known_nt_simplified.str.extract(
    "(glutamate|gaba|acetylcholine)", expand=False
)
# note that if a value has multiple matches, only the first one is kept
# e.g. 'glutamate, gaba' will be simplified to 'glutamate'
meta.known_nt_simplified.value_counts(dropna=False)

known_nt_simplified
NaN              68189
acetylcholine    52033
glutamate        11355
gaba              7516
Name: count, dtype: int64

In [28]:
# check ones that are not the same, to be safe
meta[meta.known_nt_simplified.notna()].loc[
    meta.top_nt[meta.known_nt_simplified.notna()]
    != meta.known_nt_simplified[meta.known_nt_simplified.notna()],
    ['root_id', 'cell_type',"top_nt", "known_nt", 'known_nt_noneg', 'known_nt_simplified'],
]

,root_id,cell_type,top_nt,known_nt,known_nt_noneg,known_nt_simplified
68,720575940617650722,KCab,dopamine,"acetylcholine; sNPF; acetylcholine, sNPF","acetylcholine, sNPF, acetylcholine, sNPF",acetylcholine
86,720575940628732471,KCg-m,dopamine,"acetylcholine; sNPF; acetylcholine, sNPF","acetylcholine, sNPF, acetylcholine, sNPF",acetylcholine
183,720575940624574922,KCapbp-ap1,dopamine,acetylcholine; acetylcholine,"acetylcholine, acetylcholine",acetylcholine
187,720575940636135543,KCg-m,dopamine,"acetylcholine; sNPF; acetylcholine, sNPF","acetylcholine, sNPF, acetylcholine, sNPF",acetylcholine
191,720575940622629193,KCab,dopamine,"acetylcholine; sNPF; acetylcholine, sNPF","acetylcholine, sNPF, acetylcholine, sNPF",acetylcholine
...,...,...,...,...,...,...
139129,720575940637163895,Lawf1,gaba,acetylcholine,acetylcholine,acetylcholine
139151,720575940609212508,L4,serotonin,acetylcholine,acetylcholine,acetylcholine
139157,720575940634035411,T1,gaba,acetylcholine,acetylcholine,acetylcholine
139159,720575940613672562,T1,glutamate,acetylcholine,acetylcholine,acetylcholine
139162,720575940615620263,C2,acetylcholine,gaba,gaba,gaba

In [29]:
# then use this column to replace values in top_nt column
meta.loc[:, ["top_nt"]] = meta.known_nt_simplified.fillna(meta.top_nt)

In [30]:
# first check consistency of NT within each type
meta.loc[:,["top_nt"]] = meta["top_nt"].fillna("unknown")
nt_count_per_type = meta.groupby("combined_type")["top_nt"].nunique()
nt_count_per_type

combined_type
(PLP191,PLP192)a    1
(PLP191,PLP192)b    1
(PS023,PS024)a      1
(PS023,PS024)b      1
5-HT-IR  Tan        2
                   ..
vLN26               1
vLN27               1
vLN28,vLN29         1
vpoEN               1
yDm8                3
Name: top_nt, Length: 10339, dtype: int64

In [31]:
# For those with different NT for each neuron, get the majority NT for each type
nt_conflict_types = nt_count_per_type[nt_count_per_type > 1].index

# Getting counts of top_nt for each combined_type
nt_conflict_type_counts = (
    meta[meta.combined_type.isin(nt_conflict_types)]
    .groupby(["combined_type", "top_nt"])
    .size()
)

# Convert the series to a DataFrame and reset index
nt_conflict_type_counts = nt_conflict_type_counts.reset_index(name="counts")

# Sort by combined_type and counts in descending order
nt_conflict_type_counts.sort_values(
    by=["combined_type", "counts"], ascending=[True, False], inplace=True
)

# Initialize dictionary with existing type-nt matching
type_nt = dict(zip(meta.combined_type, meta.top_nt))
# Initialize a list to keep track of types with equal top_nt counts
types_with_equal_top_nt_counts = []


# Custom function to handle ties, random selection, and record keeping
def select_random_nt_and_record_ties(df):
    max_count = df["counts"].max()
    top_nts = df[df["counts"] == max_count]
    if len(top_nts) > 1:  # If there are ties
        types_with_equal_top_nt_counts.append(
            df["combined_type"].iloc[0]
        )  # Record the type with ties
        random_nt = np.random.choice(top_nts["top_nt"].values)
        while random_nt == "unknown":
            random_nt = np.random.choice(top_nts["top_nt"].values)
        return random_nt  # Random selection among ties
    else:
        return top_nts["top_nt"].values[0]


# Loop through each type to get the top_nt, handling ties appropriately
for atype in nt_conflict_types:
    type_df = nt_conflict_type_counts[nt_conflict_type_counts["combined_type"] == atype]
    top_nt = select_random_nt_and_record_ties(type_df)
    type_nt[atype] = top_nt

len(types_with_equal_top_nt_counts)

232

In [32]:
types_with_equal_top_nt_counts

['5-HTPMPV01',
 'AL-MBDL1',
 'ALBN1',
 'AN_AVLP_38',
 'AN_AVLP_GNG_12',
 'AN_FLA_GNG_2',
 'AN_GNG_1',
 'AN_GNG_102',
 'AN_GNG_104',
 'AN_GNG_106',
 'AN_GNG_116',
 'AN_GNG_121',
 'AN_GNG_123',
 'AN_GNG_125',
 'AN_GNG_130',
 'AN_GNG_137',
 'AN_GNG_177',
 'AN_GNG_20',
 'AN_GNG_202',
 'AN_GNG_31',
 'AN_GNG_34',
 'AN_GNG_48',
 'AN_GNG_62',
 'AN_GNG_77',
 'AN_GNG_90',
 'AN_GNG_95',
 'AN_GNG_IPS_1',
 'AN_GNG_IPS_5',
 'AN_GNG_PRW_3',
 'AN_GNG_SAD_7',
 'AN_IPS_GNG_1',
 'AN_IPS_GNG_5',
 'AN_SAD_FLA_1',
 'AN_SLP_AVLP_1',
 'AN_SMP_3',
 'AN_SMP_FLA_1',
 'AN_multi_11',
 'AN_multi_87',
 'AN_multi_89',
 'AOTU024',
 'AOTU036',
 'ATL021',
 'ATL030',
 'ATL034',
 'AVLP031',
 'AVLP048',
 'AVLP155',
 'AVLP213',
 'AVLP215',
 'AVLP219a',
 'AVLP279',
 'AVLP394',
 'BM_dOcci',
 'CAPA',
 'CB0019',
 'CB0034',
 'CB0090',
 'CB0124',
 'CB0155',
 'CB0176',
 'CB0189',
 'CB0224',
 'CB0235',
 'CB0262',
 'CB0265',
 'CB0279',
 'CB0289',
 'CB0369',
 'CB0446',
 'CB0448',
 'CB0454',
 'CB0469',
 'CB0483',
 'CB0526',
 'CB0539',
 'CB0596',
 'CB0599',
 'CB0605',
 'CB0637',
 'CB0660',
 'CB0696',
 'CB0700',
 'CB0715',
 'CB0723',
 'CB0750',
 'CB0758',
 'CB0778',
 'CB0783',
 'CB0804',
 'CB0831',
 'CB0835',
 'CB0836',
 'CB0871',
 'CB0992',
 'CB1003',
 'CB1037',
 'CB1049',
 'CB1081',
 'CB1266',
 'CB1319',
 'CB1363',
 'CB1375',
 'CB1394_c',
 'CB1432',
 'CB1452',
 'CB1483',
 'CB1647',
 'CB1778',
 'CB1821',
 'CB1858',
 'CB2010',
 'CB2018',
 'CB2084',
 'CB2098',
 'CB2160',
 'CB2201',
 'CB2691',
 'CB2748',
 'CB2751',
 'CB2798',
 'CB2845',
 'CB2862',
 'CB2913',
 'CB2919',
 'CB2942',
 'CB3051',
 'CB3077',
 'CB3149',
 'CB3176',
 'CB3193',
 'CB3323',
 'CB3438',
 'CB3486',
 'CB3536',
 'CB3575',
 'CB3650',
 'CB3656',
 'CB3726',
 'CB3730',
 'CB3761',
 'CB3804',
 'CB3897',
 'CB3920',
 'CL107',
 'CL352',
 'CL360',
 'CRE024',
 'DGI',
 'DMS',
 'DNb07',
 'DNbe005',
 'DNg106',
 'DNg17',
 'DNg31',
 'DNg38',
 'DNg41',
 'DNg49',
 'DNg69',
 'DNg80',
 'DNg89',
 'DNg99',
 'DNge005',
 'DNge013',
 'DNge014',
 'DNge016',
 'DNge017',
 'DNge033',
 'DNge070',
 'DNge072',
 'DNge074',
 'DNge084',
 'DNge086',
 'DNge088',
 'DNge095',
 'DNge102',
 'DNge109',
 'DNge110',
 'DNge118',
 'DNp01',
 'DNp29',
 'DNpe054',
 'FB1F',
 'FB4K',
 'FB4_unclear',
 'H1',
 'Hugin-RG',
 'IB048',
 'JO-DA',
 'LAL072',
 'LAL132a',
 'LAL132b',
 'LAL133b',
 'LB2a-b',
 'LHAV3c1',
 'LM102a_L234-M89',
 'MsAHN',
 'PLP081',
 'PS076',
 'PS099b',
 'PS100',
 'PS116',
 'PS175',
 'PS289',
 'PVLP001',
 'PVLP081',
 'PVLP082a',
 'PVLP084',
 'SAD080',
 'SA_DMT_DMetaN_11',
 'SA_VTV_DProN_1',
 'SMP156',
 'SMP213',
 'SMP286',
 'SMP385',
 'SMP589',
 'SMPp&v1B_H01',
 'SMPp&v1B_M02',
 'TuTuAa',
 'TuTuB_a',
 'TuTuB_b',
 'WED041b',
 'WED070',
 'WED080,WED083,WED084,WED087',
 'aMe17a1',
 'aMe3',
 'cL07',
 'cLP05',
 'l2LN23',
 'lLN9',
 'mAL5B',
 'v2LN30',
 'vLN24']

In [33]:
# the types without any known nt
[atype for atype, nt in type_nt.items() if nt == "unknown"]

['720575940638707901',
 'DNge061',
 '720575940612376690',
 'ITP',
 '720575940626896145',
 '720575940624156391',
 '720575940632738259',
 '720575940621636988',
 '720575940610239608',
 '720575940623382711',
 '720575940612269283',
 'AN_GNG_204',
 'AN_GNG_124',
 '720575940614957115',
 '720575940626216720',
 '720575940621463699',
 '720575940606375772',
 '720575940610183154',
 '720575940617816661',
 '720575940635901274',
 '720575940612137895',
 '720575940621568490',
 '720575940619617919',
 '720575940628335611',
 '720575940633705560',
 '720575940637470627',
 '720575940639152117',
 '720575940638909429',
 '720575940614736699',
 '720575940611937967',
 '720575940613684274',
 '720575940625771780',
 '720575940619904380',
 '720575940630846125',
 '720575940624211202',
 '720575940611477229',
 '720575940628628055',
 '720575940618759078',
 '720575940629273130',
 '720575940618109460',
 '720575940611810001',
 '720575940628268226',
 '720575940620287820',
 '720575940623758669',
 '720575940615072662',
 '720575940625760816',
 '720575940612070769',
 '720575940618062365',
 '720575940610241860',
 '720575940638619214',
 '720575940627099934',
 '720575940628125416',
 '720575940623372502',
 '720575940618417409',
 '720575940629569040',
 '720575940638429150',
 '720575940628708092',
 '720575940628300431',
 '720575940615322023',
 '720575940620287537',
 '720575940645417764',
 '720575940617602955',
 '720575940615420306',
 '720575940624096392',
 '720575940631859151',
 '720575940616556354',
 '720575940632657208',
 '720575940631658071',
 '720575940640390973',
 '720575940613351338',
 '720575940642193909',
 '720575940605829804',
 '720575940628377231',
 '720575940619776891',
 '720575940610745156',
 '720575940617649238',
 '720575940628176128',
 '720575940623724387',
 '720575940632668729',
 '720575940609510921']

In [34]:
# update the top_nt column to be consistent within each type
meta.loc[:, ["top_nt"]] = meta.combined_type.map(type_nt)
meta

,supervoxel_id,root_id,pos_x,pos_y,pos_z,soma_x,soma_y,soma_z,nucleus_id,flow,...,vfb_id,fbbt_id,status,dimorphism,matching_notes,fru_dsx,synonyms,combined_type,known_nt_noneg,known_nt_simplified
0,78112261444987077,720575940628857210,109306.0,50491.0,3960.0,104904.0,47464.0,5461.0,2453924.0,intrinsic,...,fw138205,FBbt_20001935,NaN,isomorphic,NaN,NaN,NaN,PS180,NaN,NaN
1,82475466912542440,720575940626838909,172029.0,55635.0,1592.0,177472.0,56936.0,1429.0,7393349.0,intrinsic,...,fw000001,NaN,NaN,isomorphic,NaN,NaN,NaN,CB0924,NaN,NaN
2,83038623024880664,720575940626046919,180632.0,58664.0,1925.0,180632.0,58664.0,1925.0,7415038.0,intrinsic,...,fw000002,FBbt_20000538,NaN,isomorphic,NaN,NaN,NaN,AVLP429,NaN,NaN
3,79801523353604463,720575940630311383,133800.0,56063.0,1847.0,180728.0,61008.0,1630.0,7415013.0,intrinsic,...,fw000003,FBbt_20000260,NaN,isomorphic,NaN,NaN,NaN,AVLP151,NaN,NaN
4,83038554439606237,720575940633370649,180496.0,57448.0,2989.0,180496.0,57448.0,2989.0,7415848.0,intrinsic,...,fw000004,FBbt_00051248,NaN,isomorphic,NaN,NaN,NaN,LC27,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139237,83038485720179477,720575940618571494,181000.0,56672.0,3032.0,181000.0,56672.0,3032.0,7667349.0,intrinsic,...,fw019880,NaN,NaN,isomorphic,NaN,NaN,NaN,MLt7,NaN,NaN
139238,81632416707449383,720575940633170572,160568.0,75600.0,4130.0,160568.0,75600.0,4130.0,6918265.0,intrinsic,...,fw002173,NaN,outlier_bio,isomorphic,NaN,NaN,NaN,Li02,NaN,NaN
139239,81702991543049294,720575940650339961,161088.0,79280.0,3677.0,161088.0,79280.0,3677.0,6918344.0,intrinsic,...,fw010095,NaN,outlier_bio,isomorphic,NaN,NaN,NaN,Li02,NaN,NaN
139240,75720205111813659,720575940619997854,74280.0,57640.0,3166.0,74280.0,57640.0,3166.0,1511338.0,intrinsic,...,fw046509,NaN,NaN,isomorphic,NaN,NaN,NaN,MTe51,NaN,NaN
139241,82898435359563570,720575940632527683,179084.0,67151.0,2520.0,210200.0,67728.0,3621.0,8516311.0,intrinsic,...,fw050366,NaN,NaN,isomorphic,NaN,NaN,NaN,aMe6c,NaN,NaN

In [35]:
# for now regarding everything (ACh, Glu, GABA, Dopamine, Serotonine, ??) except for Glu and GABA to be excitatory
# first make a dictionary
nt_value = {
    "acetylcholine": 1,
    "glutamate": -1,
    "gaba": -1,
    "dopamine": 1,
    "serotonin": 1,
    "octopamine": 1,
    "unknown": 1,
}

# make coo

In [36]:
# sum synapse numbers across neuropils
conn = (
    conn_full.groupby(["pre_pt_root_id", "post_pt_root_id", "pre_type", "post_type"])
    .syn_count.sum()
    .reset_index()
)
conn

              pre_pt_root_id     post_pt_root_id pre_type post_type  syn_count
0         720575940596125868  720575940605825666      T5c     LPLC2          6
1         720575940596125868  720575940607033010      T5c       T5c          2
2         720575940596125868  720575940608552405      T5c     Tlp14          6
3         720575940596125868  720575940608661187      T5c       T5c          1
4         720575940596125868  720575940609975854      T5c      LPC2          5
...                      ...                 ...      ...       ...        ...
19771470  720575940661339777  720575940625109995     R1-6        T1          5
19771471  720575940661339777  720575940627311491     R1-6        L1         40
19771472  720575940661339777  720575940628084873     R1-6        L3         19
19771473  720575940661339777  720575940631325740     R1-6      R1-6          5
19771474  720575940661339777  720575940632702035     R1-6        L4          1

[19771475 rows x 5 columns]

In [37]:
# instead of making a dense matrix based on the edgelist above, let's make a sparse one from the edgelist directly
# first make a coo matrix
nodes = set(conn.pre_pt_root_id).union(set(conn.post_pt_root_id))
sorted_nodes = sorted(nodes)  # Convert the set to a sorted list
nodes_to_idx = {node: num for num, node in enumerate(sorted_nodes)}

# type to type connectivity
conn["pre_idx"] = conn.pre_pt_root_id.map(nodes_to_idx)
conn["post_idx"] = conn.post_pt_root_id.map(nodes_to_idx)

# Create COO matrix
row = conn["pre_idx"].values
col = conn["post_idx"].values
data = conn["syn_count"].values
matrix_size = len(nodes)
coo = coo_matrix((data, (row, col)), shape=(matrix_size, matrix_size))

# then turn it into csc matrix
csc = coo.tocsc()

# calculate the size
csc_size = csc.data.nbytes  # Size of the data array
csc_size += csc.indices.nbytes  # Size of the indices array
csc_size += csc.indptr.nbytes  # Size of the index pointer array
# number of MB
csc_size / 1e6, csc.shape

(237.814076, (139093, 139093))

In [38]:
csc

<Compressed Sparse Column sparse matrix of dtype 'int64'
	with 19771475 stored elements and shape (139093, 139093)>

In [39]:
# calculate the total post-synapses for each neuron
total_post = (
    conn_full[conn_full.post_pt_root_id.isin(nodes)]
    .groupby("post_pt_root_id")
    .syn_count.sum()
)

# some neurons have no postsynapses (receptors). Let's add those to total_post with value of 0
no_post = nodes - set(total_post.index)
no_post_dict = dict(zip(no_post, np.zeros(len(no_post), dtype=int)))
total_post = pd.concat([total_post, pd.Series(no_post_dict)])
total_post

720575940596125868     211
720575940597856265     565
720575940597944841     366
720575940598267657    1056
720575940599333574     504
                      ...
720575940606022128       0
720575940653446646       0
720575940631097849       0
720575940631601659       0
720575940624735229       0
Length: 139093, dtype: int64

In [40]:
# re-order so that it matches order of nodes
total_post = total_post.loc[sorted_nodes]
total_post

720575940596125868     211
720575940597856265     565
720575940597944841     366
720575940598267657    1056
720575940599333574     504
                      ...
720575940661335681    1549
720575940661336193     874
720575940661337217     417
720575940661338497    3377
720575940661339777      10
Length: 139093, dtype: int64

In [41]:
# Handling division by zero in case some columns have a sum of zero
# that is, where a neuron doesn't have incoming synapses
col_sums_with_inversion = np.reciprocal(
    total_post.to_numpy().astype(float), where=total_post.to_numpy() != 0
)
# Multiply each column by the inverse of its sum
inprop = csc.multiply(col_sums_with_inversion)
# and then reduce the precision to float32 to save memory
inprop = inprop.astype(np.float32)

In [42]:
# calculate the total pre-synapses for each neuron
total_pre = (
    conn_full[conn_full.pre_pt_root_id.isin(nodes)]
    .groupby("pre_pt_root_id")
    .syn_count.sum()
)

# some neurons have no presynapses (receptors). Let's add those to total_pre with value of 0
no_pre = nodes - set(total_pre.index)
no_pre_dict = dict(zip(no_pre, np.zeros(len(no_pre), dtype=int)))
total_pre = pd.concat([total_pre, pd.Series(no_pre_dict)])
# re-order so that it matches order of nodes
total_pre = total_pre.loc[sorted_nodes]

# Handling division by zero in case some rows have a sum of zero
# that is, where a neuron doesn't have incoming synapses
row_sums_with_inversion = np.reciprocal(
    total_pre.to_numpy().astype(float), where=total_pre.to_numpy() != 0
)
# Multiply each row by the inverse of its sum
outprop = csc.multiply(row_sums_with_inversion[:, None])
# and then reduce the precision to float32 to save memory
outprop = outprop.astype(np.float32)

In [43]:
sp.sparse.save_npz(
    "../data/fafb_all_neuron/fafb_syncount_all_neuron.npz",
    csc,)
sp.sparse.save_npz(
    "../data/fafb_all_neuron/fafb_inprop_all_neuron.npz",
    inprop,
)
sp.sparse.save_npz(
    "../data/fafb_all_neuron/fafb_outprop_all_neuron.npz",
    outprop,
)

## ad coo

In [44]:
# coo matrix for axo-dendritic connections
adconn["pre_idx"] = adconn.pre_root_id.map(nodes_to_idx)
adconn["post_idx"] = adconn.post_root_id.map(nodes_to_idx)

row = adconn['pre_idx'].values
col = adconn['post_idx'].values
data = adconn['syn_count'].values
matrix_size = len(nodes)
ad_coo = coo_matrix((data, (row, col)), shape=(matrix_size, matrix_size))

ad_csc = ad_coo.tocsc()

C:\Users\44745\AppData\Local\Temp\ipykernel_220664\3733787166.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  adconn["pre_idx"] = adconn.pre_root_id.map(nodes_to_idx)
C:\Users\44745\AppData\Local\Temp\ipykernel_220664\3733787166.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  adconn["post_idx"] = adconn.post_root_id.map(nodes_to_idx)

In [45]:
# calculate the total post-synapses for each neuron
total_post = (
    adconn[adconn.post_root_id.isin(nodes)]
    .groupby("post_root_id")
    .syn_count.sum()
)

# some neurons have no postsynapses (receptors). Let's add those to total_post with value of 0
no_post = nodes - set(total_post.index)
no_post_dict = dict(zip(no_post, np.zeros(len(no_post), dtype=int)))
total_post = pd.concat([total_post, pd.Series(no_post_dict)])
total_post

720575940596125868    155
720575940597856265    399
720575940597944841    144
720575940598267657    885
720575940599333574    331
                     ...
720575940622024692      0
720575940633165816      0
720575940630052857      0
720575940624941053      0
720575940621008895      0
Length: 139093, dtype: int64

In [46]:
# re-order so that it matches order of nodes
total_post = total_post.loc[sorted_nodes]
total_post

720575940596125868     155
720575940597856265     399
720575940597944841     144
720575940598267657     885
720575940599333574     331
                      ...
720575940661335681    1229
720575940661336193     411
720575940661337217      66
720575940661338497    2768
720575940661339777       0
Length: 139093, dtype: int64

In [47]:
# Handling division by zero in case some columns have a sum of zero
# that is, where a neuron doesn't have incoming synapses
col_sums_with_inversion = np.reciprocal(
    total_post.to_numpy().astype(float), where=total_post.to_numpy() != 0
)
# Multiply each column by the inverse of its sum
inprop = ad_csc.multiply(col_sums_with_inversion)
# and then reduce the precision to float32 to save memory
inprop = inprop.astype(np.float32)

In [48]:
# calculate the total pre-synapses for each neuron
total_pre = (
    adconn[adconn.pre_root_id.isin(nodes)]
    .groupby("pre_root_id")
    .syn_count.sum()
)

# some neurons have no presynapses (receptors). Let's add those to total_pre with value of 0
no_pre = nodes - set(total_pre.index)
no_pre_dict = dict(zip(no_pre, np.zeros(len(no_pre), dtype=int)))
total_pre = pd.concat([total_pre, pd.Series(no_pre_dict)])
# re-order so that it matches order of nodes
total_pre = total_pre.loc[sorted_nodes]

# Handling division by zero in case some rows have a sum of zero
# that is, where a neuron doesn't have incoming synapses
row_sums_with_inversion = np.reciprocal(
    total_pre.to_numpy().astype(float), where=total_pre.to_numpy() != 0
)
# Multiply each row by the inverse of its sum
outprop = ad_csc.multiply(row_sums_with_inversion[:, None])
# and then reduce the precision to float32 to save memory
outprop = outprop.astype(np.float32)

In [49]:
sp.sparse.save_npz(
    "../data/fafb_all_neuron/fafb_ad_syncount_all_neuron.npz",
    ad_csc,
)
sp.sparse.save_npz(
    "../data/fafb_all_neuron/fafb_ad_inprop_all_neuron.npz",
    inprop,
)
sp.sparse.save_npz(
    "../data/fafb_all_neuron/fafb_ad_outprop_all_neuron.npz",
    outprop,
)

# save meta

In [50]:
# save to csv, one row is one neuron
meta = meta.loc[
    meta.root_id.isin(nodes),
    [
        "root_id",
        "combined_type",
        "side",
        "top_nt",
        "super_class",
        "cell_class",
        "cell_sub_class",
        'ito_lee_hemilineage',
        'hartenstein_hemilineage',
    ],
]
# SAD034 was shown by Guo et al. 2022 (https://www.sciencedirect.com/science/article/pii/S0960982221017425) to be glutamatergic
meta.loc[meta.combined_type == "SAD034", "top_nt"] = "glutamate"

meta.loc[:, ["idx"]] = meta.root_id.map(nodes_to_idx)
meta.loc[:, ["sign"]] = meta.top_nt.map(nt_value)
meta.loc[:, ["coords"]] = meta.root_id.map(root_to_coords)
meta.rename(columns={"combined_type": "cell_type"}, inplace=True)

# adult, all neurons, neuron level, meta information
meta.to_csv(f"../data/fafb_all_neuron/fafb_all_neuron_meta.csv")

In [51]:
meta

,root_id,cell_type,side,top_nt,super_class,cell_class,cell_sub_class,ito_lee_hemilineage,hartenstein_hemilineage,idx,sign,coords
0,720575940628857210,PS180,left,acetylcholine,central,NaN,NaN,SMPpv2_ventral,CP1_ventral,90900,1,NaN
1,720575940626838909,CB0924,right,acetylcholine,central,NaN,NaN,VLPl2_medial,BLAv2_medial,78909,1,NaN
2,720575940626046919,AVLP429,right,acetylcholine,central,NaN,NaN,putative_primary,NaN,74855,1,NaN
3,720575940630311383,AVLP151,right,acetylcholine,central,NaN,NaN,putative_primary,putative_primary,98344,1,NaN
4,720575940633370649,LC27,right,acetylcholine,visual_projection,NaN,NaN,NaN,NaN,112637,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
139237,720575940618571494,MLt7,right,acetylcholine,optic,ME>LO,NaN,NaN,NaN,35797,1,NaN
139238,720575940633170572,Li02,right,acetylcholine,optic,LO,NaN,NaN,NaN,111842,1,NaN
139239,720575940650339961,Li02,right,acetylcholine,optic,LO,NaN,NaN,NaN,137234,1,NaN
139240,720575940619997854,MTe51,left,acetylcholine,optic,ME>LO,NaN,NaN,NaN,41495,1,NaN
139241,720575940632527683,aMe6c,right,glutamate,optic,NaN,NaN,NaN,NaN,109255,-1,NaN